/**
 * 第 1–4 周：每日教材完整内容（阶段 1：建立输出习惯）
 * 每项含：跟读、句型、词汇、对话、角色扮演、模拟、复盘题
 */

const S = (en, zh) => ({ en, zh });
const D = (speaker, en, zh) => ({ speaker, en, zh });

export const weeks1to4Detailed = [
  {
    weekNumber: 1,
    weeklyGoal: '完成「创始人自我介绍 + 公司叙事」基础闭环，敢在 60 秒内讲清楚你是谁、公司做什么、为何重要。',
    focusAbility: '输出启动：发音节奏、完整句输出、避免中式拼句。',
    themes: '自我介绍 / 公司定位 / 产品一句话 / 市场方向',
    weeklyReviewTask: '录音 2 分钟：用英文介绍自己与公司，并列出 3 个本周最顺手的句型。',
    ceoWeeklyFocus: '本周 CEO 表达重点：用一条清晰主线串联「我 — 公司 — 价值」。',
    days: [
      {
        dayInWeek: 1,
        themeZh: '创始人自我介绍与公司一句话',
        themeEn: 'Founder intro in one clear arc',
        todayFocus: 'Let me briefly introduce myself.',
        shadowing: [
          S('Let me briefly introduce myself.', '让我简单介绍一下自己。'),
          S("I'm the founder of a company focused on creator tools.", '我是一家专注创作者工具公司的创始人。'),
          S('We help creators ship content faster with better hardware workflows.', '我们用更好的硬件工作流帮助创作者更快产出内容。'),
          S('My background is in product and supply chain.', '我的背景在产品与供应链。'),
          S('I spend most of my time on strategy, partnerships, and execution.', '我大部分时间花在战略、合作与执行上。'),
          S('I work across China and the US with our global team.', '我与分布在中美的团队一起协作。'),
          S('Nice to meet you — I appreciate your time today.', '很高兴认识您，感谢您今天抽时间。'),
        ],
        expressions: [
          S('I’m responsible for overall direction and key partnerships.', '我负责整体方向与关键合作关系。'),
          S('Our mission is to reduce friction for creators on the go.', '我们的使命是降低移动创作中的摩擦。'),
          S('We are still early, but growth has been strong in the last quarter.', '我们仍在早期，但上季度增长强劲。'),
          S('I’m excited to explore how we can collaborate.', '我很期待探讨我们如何合作。'),
          S('If helpful, I can share more context on our roadmap.', '如需要，我可以补充路线图背景。'),
          S('I prefer direct communication — please challenge my assumptions.', '我偏好直接沟通，欢迎挑战我的假设。'),
          S('My English is a work in progress; I care about clarity.', '我的英语仍在进步，我更在意表达清晰。'),
          S('Let me know what success looks like on your side.', '请告诉我你们侧的成功标准是什么。'),
        ],
        vocabulary: [
          S('founder', '创始人'),
          S('creator economy', '创作者经济'),
          S('workflow', '工作流'),
          S('partnership', '合作关系'),
          S('roadmap', '路线图'),
          S('traction', '牵引力/进展证明'),
          S('alignment', '对齐'),
          S('stakeholder', '相关方'),
        ],
        dialogue: [
          D('Host', 'William, could you kick us off with a quick intro?', 'William，能先做个简短介绍吗？'),
          D('You', "Sure — I'm the founder of a creator-tools company. We build portable gear for mobile shooting.", '当然，我是一家创作者工具公司的创始人，我们做移动拍摄的便携设备。'),
          D('Host', 'What problem are you solving?', '你们解决什么问题？'),
          D('You', 'Creators lose time setting up gear. We make setup fast so they can focus on storytelling.', '创作者在搭建设备上浪费时间，我们让搭建更快，让他们专注讲故事。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：30 秒电梯介绍',
          brief: '你在美国展会展台，遇到一位渠道采购。用 30–45 秒完成自我介绍 + 公司一句话 + 一个具体问题（了解对方渠道）。',
          prompts: [
            '开场致谢与姓名职位',
            '公司做什么、为谁服务',
            '一个想问对方的具体问题',
          ],
        },
        simulation: {
          titleZh: '模拟：投资人咖啡聊天开场',
          context: '对方问："What are you building?" 你需要避免技术堆砌，用业务语言回答。',
          objectives: [
            '用 3 句话完成：品类 / 用户 / 差异化',
            '主动反问对方关注的指标（margin / velocity / brand）',
            '用平稳语速，不要加快',
          ],
        },
        reflectionQuestions: [
          '今天哪一句自我介绍最顺口？为什么？',
          '哪个英文词最容易卡壳？准备一个简单的替代表达。',
          '如果把公司介绍缩短到 15 秒，你会删掉什么？',
        ],
        oralTaskZh: '朗读并录音：自我介绍 6 句 + 公司使命 2 句，各重复 3 遍。',
      },
      {
        dayInWeek: 2,
        themeZh: '公司叙事：市场、优势、扩张',
        themeEn: 'Company narrative: market & edge',
        todayFocus: 'We are expanding our business in the US market.',
        shadowing: [
          S('We are expanding our business in the US market.', '我们正在拓展美国市场业务。'),
          S('Our main strength is product innovation and supply chain efficiency.', '我们的主要优势在产品创新与供应链效率。'),
          S('We work with creators, retailers, and distribution partners globally.', '我们与全球的创作者、零售商与分销伙伴合作。'),
          S('The US is strategically important for brand credibility.', '美国市场对品牌背书非常关键。'),
          S('We are building a local team to support partners on the ground.', '我们正在搭建本地团队以支持在地伙伴。'),
          S('Our differentiation is speed from concept to shelf.', '我们的差异化是从概念到上架的速度。'),
          S('We are not chasing hype — we are building durable products.', '我们不追热点，在做耐用的产品。'),
        ],
        expressions: [
          S('We see strong pull from independent retail.', '我们看到独立零售端的强需求。'),
          S('Our bottleneck is distribution, not demand.', '瓶颈在分销，不是需求。'),
          S('We can commit to tighter lead times this quarter.', '本季度我们可以承诺更短的交期。'),
          S('We prefer partners who think long-term.', '我们更偏好长期思维的伙伴。'),
          S('Let me share two proof points from recent launches.', '我分享两个近期上线的佐证。'),
          S('We are optimizing for repeat purchase, not one-off spikes.', '我们优化复购，而不是一次性爆发。'),
          S('Happy to walk through our channel strategy.', '乐意逐步讲解我们的渠道策略。'),
          S('If it helps, I can connect you with our US lead.', '如需要，我可以介绍我们在美国的负责人。'),
        ],
        vocabulary: [
          S('go-to-market', '市场进入策略'),
          S('distribution', '分销'),
          S('retailer', '零售商'),
          S('DTC', '直面消费者'),
          S('wholesale', '批发'),
          S('lead time', '交期'),
          S('SKU', '单品'),
          S('sell-through', '动销'),
        ],
        dialogue: [
          D('Buyer', 'Why should we prioritize your brand?', '为什么我们要优先上你们的品牌？'),
          D('You', 'Because we convert shelf space into velocity — our sell-through is above category average.', '因为我们能把货架空间变成动销速度——我们的动销高于品类均值。'),
          D('Buyer', 'What support do you provide?', '你们提供什么支持？'),
          D('You', 'Co-marketing, training, and quarterly reviews on inventory health.', '联合营销、培训，以及按季度的库存健康复盘。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：向渠道解释「为何进美国」',
          brief: '你是创始人，对美方合伙人解释中国市场成功与美国策略的连续性。',
          prompts: ['用两个数据点支撑', '说明资源投入（团队/库存/营销）', '提出下一步会议目标'],
        },
        simulation: {
          titleZh: '模拟：1 分钟「公司优势」陈述',
          context: '对方时间紧，只给你 60 秒。',
          objectives: ['先讲结论再讲证据', '避免形容词堆砌', '最后一句话要可行动（约下次会议）'],
        },
        reflectionQuestions: [
          '哪一句最能代表你公司的「非你不可」？',
          '如果把优势压缩成三个英文关键词，会是哪三个？',
          '今天是否有一次把句子说得太长？如何拆句？',
        ],
        oralTaskZh: '用英文回答：Why US now? Why you? Why this partner? 各 20 秒。',
      },
      {
        dayInWeek: 3,
        themeZh: '日常工作安排与跨时区沟通',
        themeEn: 'Routines & async updates',
        todayFocus: 'I will follow up with a written summary.',
        shadowing: [
          S('I will follow up with a written summary after this call.', '会后我会用文字摘要跟进。'),
          S('Let’s align on owners and deadlines.', '我们对齐负责人与截止日期。'),
          S('I am available between 9 and 11 a.m. Pacific.', '我在太平洋时间 9–11 点方便。'),
          S('Please flag anything that is blocking you.', '请标记任何阻塞你的事项。'),
          S('I prefer Slack for quick questions and email for decisions.', '快捷问题用 Slack，决策类用邮件。'),
          S('Let’s keep the meeting to thirty minutes.', '我们把会议控制在 30 分钟。'),
          S('If it is urgent, ping me directly.', '如果紧急，直接找我。'),
        ],
        expressions: [
          S('Can you update the doc by EOD?', '能在今天下班前更新文档吗？'),
          S('I need visibility on the timeline.', '我需要看到时间线的可见性。'),
          S('Let’s avoid duplicate work — who owns this?', '避免重复劳动——谁负责？'),
          S('I will review async and reply tonight.', '我会异步查看并今晚回复。'),
          S('Let’s move this to a thread with finance copied.', '我们把这话题转到抄送财务的线程里。'),
          S('I am OOO tomorrow — please escalate to Alex.', '我明天不在，请找 Alex 升级。'),
          S('Thanks for the heads-up.', '感谢提前告知。'),
          S('Let’s document the decision so nothing drifts.', '把决策记下来，避免走样。'),
        ],
        vocabulary: [
          S('EOD', '当日结束'),
          S('OOO', '不在办公室'),
          S('visibility', '可见性/掌握情况'),
          S('escalate', '升级上报'),
          S('async', '异步'),
          S('thread', '消息串'),
          S('owner', '负责人'),
          S('deadline', '截止日期'),
        ],
        dialogue: [
          D('PM', 'We might slip by two days on QA.', 'QA 可能延误两天。'),
          D('You', "Thanks for flagging early. What's the smallest cut to protect the launch date?", '感谢提早说。为保护上线日，最小裁剪是什么？'),
          D('PM', 'We can defer non-critical bugs to v1.1.', '非关键 bug 可延到 v1.1。'),
          D('You', "Let's document the scope cut and communicate to stakeholders.", '记录范围裁剪并同步相关方。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：说明延误 + 给方案',
          brief: '向美国同事说明交付风险，并提出两项缓解措施与一个决策请求。',
          prompts: ['事实 → 影响 → 方案 → 需要对方什么'],
        },
        simulation: {
          titleZh: '模拟：跨时区「明天前需要回复」',
          context: '你要催进度但不引发对抗。',
          objectives: ['先肯定努力', '明确截止与原因', '提供协助选项'],
        },
        reflectionQuestions: [
          '今天你用的最自然的一句「催进度」英文是什么？',
          '哪句话听起来太强硬？如何 softer 但不变更要求？',
          '写一封 5 句话以内的 follow-up email 草稿要点。',
        ],
        oralTaskZh: '练习 6 句「异步协作」表达，录音对比语速与停顿。',
      },
      {
        dayInWeek: 4,
        themeZh: '会议基础：开场、控时、收尾',
        themeEn: 'Meeting basics',
        todayFocus: "Let's align on the next steps.",
        shadowing: [
          S('Let’s get started — thanks for joining.', '我们开始，感谢参加。'),
          S('Today we’ll focus on three key issues.', '今天聚焦三个关键议题。'),
          S('First, let’s review last week’s progress.', '先回顾上周进展。'),
          S('What’s the biggest blocker right now?', '当前最大阻塞是什么？'),
          S('Let’s align on the next steps.', '我们对齐下一步。'),
          S('I’ll summarize decisions before we wrap.', '结束前我会总结决策。'),
          S('If no questions, we’ll end five minutes early.', '若无问题，我们提前五分钟结束。'),
        ],
        expressions: [
          S('Let’s timebox this topic to ten minutes.', '这话题限时十分钟。'),
          S('I want to hear from engineering first.', '我想先听工程角度。'),
          S('Let’s park detailed design and follow up offline.', '细节设计先搁置，线下跟进。'),
          S('Can we agree on a decision today?', '我们今天能形成决策吗？'),
          S('I’ll own the follow-up with legal.', '我来负责与法务跟进。'),
          S('Please send recap notes in the thread.', '请把纪要发到线程里。'),
          S('Let’s schedule a follow-up if we run out of time.', '若时间不够，我们另约跟进会。'),
          S('I appreciate the direct feedback.', '感谢直接反馈。'),
        ],
        vocabulary: [
          S('timebox', '限时讨论'),
          S('parking lot', '暂存清单'),
          S('recap', '纪要/回顾'),
          S('blocker', '阻塞项'),
          S('decision', '决策'),
          S('follow-up', '后续跟进'),
          S('agenda', '议程'),
          S('action item', '行动项'),
        ],
        dialogue: [
          D('You', 'Agenda: updates, risks, decisions.', '议程：进展、风险、决策。'),
          D('Eng', 'Risk: API rate limits in production.', '风险：生产环境 API 限速。'),
          D('You', 'What’s the mitigation and who owns it?', '缓释方案是什么，谁负责？'),
          D('You', 'Decision: ship with throttling and monitor for 48 hours.', '决策：先上限流并监控 48 小时。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：主持 15 分钟站会',
          brief: '用英文串场：开场 → 每人 1 分钟 → 汇总阻塞 → 下一步。',
          prompts: ['用连接词保持节奏', '不断重复 next owner / by when'],
        },
        simulation: {
          titleZh: '模拟：客户会议超时',
          context: '还剩 5 分钟，但对方还在扩展需求。',
          objectives: ['礼貌打断', '提议另约', '明确今天带走的决策'],
        },
        reflectionQuestions: [
          '今天你作为主持人，哪一句最有效？',
          '哪个时刻你差点抢话？如何避免？',
          '写一句你下周要用的英文会议开场白。',
        ],
        oralTaskZh: '完整演练：会议开场 + 议题切换 + 收尾总结，各录一遍。',
      },
      {
        dayInWeek: 5,
        themeZh: '数字与 traction：讲清楚增长',
        themeEn: 'Metrics storytelling',
        todayFocus: 'Revenue grew 35% quarter over quarter.',
        shadowing: [
          S('Revenue grew thirty-five percent quarter over quarter.', '收入环比上季度增长 35%。'),
          S('Our repeat purchase rate improved meaningfully.', '我们的复购率显著提升。'),
          S('We are still optimizing unit economics.', '我们仍在优化单位经济模型。'),
          S('CAC is high, but payback is within acceptable range.', '获客成本高，但回收周期在可接受范围。'),
          S('Inventory turns improved after we adjusted assortment.', '调整品类组合后库存周转改善。'),
          S('We track weekly sell-through with key retailers.', '我们与核心零售商按周看动销。'),
          S('The next milestone is expanding shelf placement.', '下一个里程碑是扩大货架覆盖。'),
        ],
        expressions: [
          S('The headline metric is sell-through, not shipments.', '关键指标是动销，不是出货量。'),
          S('We are seeing pull, not just push.', '我们看到拉力，而不只是推动。'),
          S('Let me share the latest cohort curve.', '我分享最新的队列曲线。'),
          S('We are conservative in forecasting.', '我们的预测偏保守。'),
          S('The bottleneck is distribution capacity.', '瓶颈在分销能力。'),
          S('Happy to share the data room highlights.', '乐意分享数据室要点。'),
          S('We measure quality by returns and NPS.', '用退货率与 NPS 衡量质量。'),
          S('We will update the board monthly on these KPIs.', '我们按月向董事会更新这些 KPI。'),
        ],
        vocabulary: [
          S('QoQ', '环比季度'),
          S('YoY', '同比年度'),
          S('cohort', '队列/同期群'),
          S('margin', '毛利/利润空间'),
          S('inventory', '库存'),
          S('forecast', '预测'),
          S('KPI', '关键指标'),
          S('NPS', '净推荐值'),
        ],
        dialogue: [
          D('Partner', 'How do you know demand is real?', '你怎么知道需求真实？'),
          D('You', 'Sell-through and reorders — not sell-in alone.', '动销与返单，而不是只靠压货。'),
          D('Partner', 'What is your return rate?', '退货率多少？'),
          D('You', 'Below category benchmark; I can send the latest cut by retailer.', '低于品类基准；可按零售商给你最新切片。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：用 60 秒讲 traction',
          brief: '面对美方顾问，先结论后数据，避免堆数字。',
          prompts: ['1 个 headline 指标', '1 个证明点', '1 个下一步'],
        },
        simulation: {
          titleZh: '模拟：被追问「是不是在烧钱换增长」',
          context: '保持冷静，用指标与策略回答。',
          objectives: ['承认投入', '解释回收', '给出观察窗口'],
        },
        reflectionQuestions: [
          '哪个英文数字你念得最不顺？练三遍。',
          '哪一句让你的叙事更有「CEO 感」？',
          '如果把增长故事讲给非行业人，你会删什么术语？',
        ],
        oralTaskZh: '练习读数字：百分比、货币、时间区间，各 5 句。',
      },
      {
        dayInWeek: 6,
        themeZh: '邮件与消息：决策、行动项、礼貌边界',
        themeEn: 'Written executive comms',
        todayFocus: 'Decision needed by Thursday.',
        shadowing: [
          S('Decision needed by Thursday — please see options A and B.', '周四前需决策——请看 A/B 方案。'),
          S('My recommendation is B due to speed and risk.', '我推荐 B，因为速度与风险。'),
          S('If silent by EOD, I will proceed with the default.', '若今日下班前无回复，我将按默认执行。'),
          S('Flagging risk: supplier may delay by one week.', '风险提示：供应商可能延误一周。'),
          S('Please review the attached one-pager.', '请查看附件一页纸摘要。'),
          S('Happy to jump on a quick call if faster.', '若更快，我可以快速电话。'),
          S('Thanks for pushing this forward.', '感谢推进。'),
        ],
        expressions: [
          S('TL;DR: we should ship the smaller scope.', '太长不看：我们应上更小范围。'),
          S('I need a yes/no on budget today.', '今天需要预算上是/否。'),
          S('Looping in legal for visibility.', '抄送法务同步信息。'),
          S('Let’s avoid decision drift — please confirm.', '避免决策漂移——请确认。'),
          S('I’m available for a 15-minute decision sync.', '我可参加 15 分钟决策同步。'),
          S('This is time-sensitive because of manufacturing slots.', '因制造排期，这件事时间敏感。'),
          S('Appreciate everyone’s urgency here.', '感谢大家的紧迫感。'),
          S('I will send a recap after the call.', '会后我会发纪要。'),
        ],
        vocabulary: [
          S('TL;DR', '太长不看摘要'),
          S('one-pager', '一页纸摘要'),
          S('default', '默认选项'),
          S('time-sensitive', '时间敏感'),
          S('visibility', '同步可见'),
          S('approval', '批准'),
          S('scope', '范围'),
          S('trade-off', '权衡'),
        ],
        dialogue: [
          D('You', 'Subject: Decision needed — packaging v2', '主题：需要决策——包装 v2'),
          D('You', 'Option A is cheaper; Option B improves retail conversion.', 'A 更便宜；B 提升零售转化。'),
          D('Ops', 'B adds two days to lead time.', 'B 增加两天交期。'),
          D('You', 'I still choose B — conversion matters more this quarter.', '仍选 B——本季度转化更重要。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：口头转写邮件结构',
          brief: '把一封中文邮件用英文口头说一遍：背景 / 选项 / 建议 / 截止。',
          prompts: ['用短句', '主动作项', '避免模糊词 soon'],
        },
        simulation: {
          titleZh: '模拟：对方迟迟不回邮件',
          context: '你要催决策但不失礼。',
          objectives: ['重申截止', '说明后果', '提供协助'],
        },
        reflectionQuestions: [
          '你今天写/说了哪句「要决策」最有力？',
          '哪句太绕？如何改成主动语态？',
          '列出 3 个你常用的邮件开头英文句式。',
        ],
        oralTaskZh: '朗读 6 句「决策邮件」模板句，并替换自己的项目词。',
      },
      {
        dayInWeek: 7,
        themeZh: '第 1 周复盘：输出自信与下一步',
        themeEn: 'Week 1 review',
        todayFocus: 'I am building a daily speaking habit.',
        shadowing: [
          S('I am building a daily speaking habit as a founder.', '作为创始人，我在建立每日开口习惯。'),
          S('Clarity matters more than sounding perfect.', '清晰比听起来完美更重要。'),
          S('I will keep my sentences short and direct.', '我会保持句子短而直接。'),
          S('I want feedback on pacing and structure.', '我希望反馈节奏与结构。'),
          S('Next week I will focus on meetings and updates.', '下周我会聚焦会议与更新。'),
          S('I am comfortable pausing to think.', '我允许自己停顿思考。'),
          S('Thank you for holding me accountable.', '感谢你督促我坚持。'),
        ],
        expressions: [
          S('This week I improved my intro narrative.', '本周我改进了自我介绍叙事。'),
          S('I still struggle with long sentences.', '我仍容易把句子说太长。'),
          S('I will drill transitions between topics.', '我会练习话题之间过渡。'),
          S('I need more reps in real meetings.', '我需要在真实会议里多练。'),
          S('I will record myself for five minutes daily.', '我会每天录 5 分钟自己。'),
          S('My goal is to speak with calm confidence.', '目标是平静自信地表达。'),
          S('I will prepare three go-to phrases for next week.', '我会准备三个下周常用短语。'),
          S('Progress is non-linear — consistency wins.', '进步非线性——坚持赢。'),
        ],
        vocabulary: [
          S('accountability', '问责/督促'),
          S('reps', '重复练习次数'),
          S('pacing', '节奏'),
          S('narrative', '叙事'),
          S('confidence', '自信'),
          S('consistency', '一致性/坚持'),
          S('feedback', '反馈'),
          S('milestone', '里程碑'),
        ],
        dialogue: [
          D('Coach', 'What was your win this week?', '本周你的收获？'),
          D('You', 'I can introduce the company without reading notes.', '我可以不看稿介绍公司。'),
          D('Coach', 'What will you drill next week?', '下周练什么？'),
          D('You', 'Meeting transitions and asking better questions.', '会议过渡与更好的提问。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：周复盘口头版',
          brief: '用英文做 90 秒周复盘：结果 / 卡点 / 下周重点。',
          prompts: ['各 30 秒', '用具体例子', '最后一句话要行动导向'],
        },
        simulation: {
          titleZh: '模拟：合伙人问你「这周英语练了什么」',
          context: '用业务语言回答，而不是学习细节堆砌。',
          objectives: ['连接业务场景', '展示可复用句型', '提出需要支持'],
        },
        reflectionQuestions: [
          '本周最能带走的三句英文是什么？',
          '你最想在真实场景里试用的表达是哪一句？',
          '下周一天中最适合练口语的 30 分钟窗口是？',
        ],
        oralTaskZh: '完整复盘录音：2 分钟英文，不回放修改，先完成再迭代。',
      },
    ],
  },
  {
    weekNumber: 2,
    weeklyGoal: '把「会议英语」从能听懂变成能控场：议程、时间、决策与后续跟进。',
    focusAbility: '会议主持、提问、总结、邮件收口。',
    themes: '议程 / 时间盒 / 决策 / 纪要',
    weeklyReviewTask: '写一封英文会议纪要模板（5–8 句），并口头念两遍。',
    ceoWeeklyFocus: '本周 CEO 表达重点：让每一句话都能推动决策或行动。',
    days: [
      {
        dayInWeek: 1,
        themeZh: '会议开场与议程设定',
        themeEn: 'Opening & framing',
        todayFocus: "Today we'll focus on three key issues.",
        shadowing: [
          S('Thanks everyone — let’s stay focused and respectful of time.', '感谢各位——保持专注并尊重时间。'),
          S("Today we'll focus on three key issues.", '今天聚焦三个关键问题。'),
          S('Goal: leave with clear decisions and owners.', '目标：带着明确决策与负责人离开。'),
          S('If we drift, I will bring us back to the agenda.', '若跑题，我会拉回议程。'),
          S('Please hold detailed debates for offline threads.', '细节争论请放到线下线程。'),
          S('Let’s start with a two-minute context from product.', '先请产品用两分钟给背景。'),
          S('I will capture action items live.', '我会现场记录行动项。'),
        ],
        expressions: [
          S('The purpose of this meeting is to decide X.', '会议目的是决定 X。'),
          S('We are not solving everything today — we are deciding the next step.', '今天不求解决所有——只决定下一步。'),
          S('Let’s hear two perspectives, then decide.', '先听两种观点，再决策。'),
          S('Can we quantify the impact?', '能否量化影响？'),
          S('What would change your mind?', '什么会改变你的判断？'),
          S('I propose we timebox discussion to eight minutes.', '建议讨论限时八分钟。'),
          S('Let’s vote with a quick thumb signal.', '我们快速举手表态。'),
          S('If no objection, we will treat silence as agreement.', '若无异议，沉默视为同意。'),
        ],
        vocabulary: [
          S('frame', '定调/框架'),
          S('outcome', '结果'),
          S('decision log', '决策记录'),
          S('consent', '同意'),
          S('objection', '异议'),
          S('parking lot', '暂存区'),
          S('offline', '线下/异步'),
          S('facilitator', '主持人'),
        ],
        dialogue: [
          D('You', 'Opening: decision on vendor and launch date.', '开场：供应商与上线日决策。'),
          D('Eng', 'Vendor B is cheaper but slower.', 'B 更便宜但更慢。'),
          D('You', 'Trade-off: cost vs schedule risk — what is acceptable?', '权衡：成本 vs 排期风险——可接受边界？'),
          D('You', 'Decision: Vendor A, launch March 12.', '决策：供应商 A，3 月 12 上线。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：给一场 30 分钟会议定调',
          brief: '说明目的、规则、预期产出，并邀请第一位发言者。',
          prompts: ['30 秒开场', '议程三点', '时间规则'],
        },
        simulation: {
          titleZh: '模拟：两位高管争论跑题',
          context: '你要礼貌打断并提议线下继续。',
          objectives: ['复述分歧', '提议机制', '回到决策点'],
        },
        reflectionQuestions: [
          '哪一句开场让你最有掌控感？',
          '你今天最容易忘记的英文连接词是什么？',
          '下次会议你要减少哪种无效表达？',
        ],
        oralTaskZh: '背诵并跟读 6 句「定调」句型，替换自己的会议主题词。',
      },
      {
        dayInWeek: 2,
        themeZh: '进度追问与阻塞处理',
        themeEn: 'Progress & blockers',
        todayFocus: "What's the biggest blocker right now?",
        shadowing: [
          S('Walk me through what shipped last week.', '说说上周交付了什么。'),
          S('What is not moving — and why?', '什么没动——原因是什么？'),
          S('What is the biggest blocker right now?', '当前最大阻塞是什么？'),
          S('Who is waiting on whom?', '谁在等谁？'),
          S('What is the fastest path to unblock?', '最快的解阻路径是什么？'),
          S('Do we need a decision from me today?', '今天需要我做决策吗？'),
          S('Let’s assign an owner before we leave.', '离开前指定负责人。'),
        ],
        expressions: [
          S('I need a crisp status — green / yellow / red.', '我要清晰状态：绿/黄/红。'),
          S('Yellow means at risk unless we intervene.', '黄表示若不介入就有风险。'),
          S('Red means we will miss the date without a scope change.', '红表示不改范围就会延期。'),
          S('What is the single dependency?', '单一依赖是什么？'),
          S('Can we parallelize any work?', '有没有可并行的工作？'),
          S('I will escalate to leadership if needed.', '需要的话我会向管理层升级。'),
          S('Let’s not confuse busy with progress.', '别把忙碌当成进展。'),
          S('What help do you need from me in the next 48 hours?', '48 小时内需要我什么支持？'),
        ],
        vocabulary: [
          S('blocker', '阻塞'),
          S('dependency', '依赖'),
          S('parallelize', '并行化'),
          S('scope', '范围'),
          S('risk', '风险'),
          S('mitigation', '缓释'),
          S('status', '状态'),
          S('intervention', '介入'),
        ],
        dialogue: [
          D('Lead', 'We are blocked on design approval.', '我们卡在设计审批。'),
          D('You', 'What is the minimum approval to proceed?', '最低限度批什么可以继续？'),
          D('Lead', 'Just the layout grid.', '只要版式网格。'),
          D('You', 'Decision: approve grid today; polish can follow.', '决策：今天批网格；美化可后补。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：1 on 1 进度对话',
          brief: '你是创始人，听汇报并逼出「一个阻塞 + 一个行动」。',
          prompts: ['先听事实', '再问原因', '最后要承诺'],
        },
        simulation: {
          titleZh: '模拟：团队互相甩锅',
          context: '你要对齐事实并指定 owner。',
          objectives: ['不评判人格', '对齐时间线', '明确下一步'],
        },
        reflectionQuestions: [
          '哪一句追问最有效？',
          '你如何英文表达「我不接受模糊」但不伤人？',
          '写一个你明天就能用的 blocker 问句。',
        ],
        oralTaskZh: '跟读 7 句追问句，并把其中 3 句改成你业务的真实现状。',
      },
      {
        dayInWeek: 3,
        themeZh: '反馈：表扬、纠正、期望',
        themeEn: 'Feedback that moves execution',
        todayFocus: 'I want you to take ownership of this project.',
        shadowing: [
          S('I appreciated how you handled the launch incident.', '我很认可你处理上线事故的方式。'),
          S('The impact was real — customers noticed.', '影响真实——客户有感知。'),
          S('Next time, I want earlier escalation.', '下次我希望更早升级。'),
          S('I want you to take ownership of this project end-to-end.', '我希望你端到端负责这个项目。'),
          S('Here is what great looks like in two weeks.', '两周内「好」的标准是这样。'),
          S('I am not questioning intent — I am focusing on outcomes.', '我不质疑动机——我看结果。'),
          S('What support do you need from me?', '你需要我什么支持？'),
        ],
        expressions: [
          S('Your strength is X; your growth edge is Y.', '你的强项是 X；成长点是 Y。'),
          S('Let’s separate the behavior from the person.', '把行为与人分开。'),
          S('I need more proactive communication.', '我需要更主动的沟通。'),
          S('Can we agree on weekly checkpoints?', '我们能否约定每周检查点？'),
          S('I will be direct because I respect your time.', '我会直接，因为尊重你的时间。'),
          S('If this repeats, we will change the process.', '若再发生，我们会改流程。'),
          S('I believe you can level up here.', '我相信你能在这里升级。'),
          S('Let’s document expectations in writing.', '把期望写下来。'),
        ],
        vocabulary: [
          S('ownership', '主人翁意识'),
          S('escalation', '升级'),
          S('expectation', '期望'),
          S('behavior', '行为'),
          S('outcome', '结果'),
          S('check-in', '一对一沟通'),
          S('coaching', '辅导'),
          S('performance', '绩效'),
        ],
        dialogue: [
          D('You', 'Feedback: communication was late.', '反馈：沟通偏晚。'),
          D('Employee', 'I thought it was under control.', '我以为可控。'),
          D('You', 'Under control is not the same as visible.', '可控不等于可见。'),
          D('You', 'Going forward: flag risks within 24 hours.', '以后：24 小时内标记风险。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：1 on 1 反馈',
          brief: '用 SBI 结构（情境-行为-影响）给一条真实场景的反馈。',
          prompts: ['情境一句话', '行为具体', '影响业务', '下一步协议'],
        },
        simulation: {
          titleZh: '模拟：对方情绪防御',
          context: '保持冷静，复述对方观点，再回到标准。',
          objectives: ['先对齐感受', '回到事实', '约定机制'],
        },
        reflectionQuestions: [
          '你今天最难说出口的英文词是什么？',
          '哪一句反馈太模糊？如何更具体？',
          '写下一句「高期望但尊重」的英文收束语。',
        ],
        oralTaskZh: '朗读 6 句反馈句式，替换为你的团队语境。',
      },
      {
        dayInWeek: 4,
        themeZh: '任务布置：截止、标准、资源',
        themeEn: 'Delegation with clarity',
        todayFocus: 'I need this completed by Friday.',
        shadowing: [
          S('I need this completed by Friday EOD Pacific.', '太平洋时间周五下班前需要完成。'),
          S('Definition of done includes QA sign-off.', '完成标准包含 QA 签字。'),
          S('If you hit a blocker, ping me immediately.', '遇到阻塞立刻找我。'),
          S('Priority is P0 — everything else is secondary.', '优先级 P0，其它靠后。'),
          S('I trust your judgment on implementation details.', '实现细节我信任你的判断。'),
          S('Please send a short written recap when finished.', '完成后请发简短文字复盘。'),
          S('Let’s not optimize prematurely — ship the MVP.', '别过早优化——先上 MVP。'),
        ],
        expressions: [
          S('This is the non-negotiable deadline.', '这是不可让步的截止。'),
          S('Scope is frozen unless we explicitly change it.', '范围已冻结除非明确变更。'),
          S('I will remove distractions from your plate.', '我会帮你清掉干扰项。'),
          S('If you need budget, propose a number.', '需要预算就提数字。'),
          S('I want a plan A and a cheaper plan B.', '我要 A 方案和更省钱的 B。'),
          S('Let’s align on success metrics before you start.', '开始前对齐成功指标。'),
          S('I expect daily micro-updates in the thread.', '我希望线程里每日微更新。'),
          S('If you disagree, push back now — not later.', '若不同意现在反对——别拖到后面。'),
        ],
        vocabulary: [
          S('P0', '最高优先级'),
          S('MVP', '最小可用产品'),
          S('sign-off', '签字确认'),
          S('definition of done', '完成定义'),
          S('push back', '反对/提出异议'),
          S('plate', '手头任务盘'),
          S('budget', '预算'),
          S('milestone', '里程碑'),
        ],
        dialogue: [
          D('You', 'Deliverable: pricing page copy + legal review.', '交付：定价页文案 + 法务审。'),
          D('PM', 'Legal may take a week.', '法务可能要一周。'),
          D('You', 'Then ship copy first with a disclaimer banner.', '那就先上线文案加免责声明条。'),
          D('You', 'Owner: you; deadline: Wednesday.', '负责人：你；截止：周三。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：布置一个跨部门任务',
          brief: '说清楚目标、截止、标准、资源、升级路径。',
          prompts: ['用编号列点', '复述对方理解', '确认风险'],
        },
        simulation: {
          titleZh: '模拟：对方说「资源不够」',
          context: '你要谈判资源或砍范围。',
          objectives: ['问缺什么', '给选项', '定决策'],
        },
        reflectionQuestions: [
          '你今天布置任务时最清晰的一句是什么？',
          '哪句容易被误解？如何加限定词？',
          '用英文写三条「完成标准」给真实项目。',
        ],
        oralTaskZh: '练习「截止 + 标准 + 负责人」三件套，连说 10 遍提速不降质。',
      },
      {
        dayInWeek: 5,
        themeZh: '客户/合作方会议：专业与可信',
        themeEn: 'Partner-facing polish',
        todayFocus: 'We are looking for a long-term partnership.',
        shadowing: [
          S('Thanks for the partnership — we take it seriously.', '感谢合作——我们很认真。'),
          S('We are looking for a long-term partnership, not a one-off deal.', '我们寻求长期合作，不是一锤子买卖。'),
          S('We prefer transparency on constraints.', '我们偏好对约束透明。'),
          S('If something is risky, we will say it early.', '若有风险我们会早说。'),
          S('We want mutual success, not winner-takes-all.', '要共赢，不是零和。'),
          S('Let’s align incentives before we negotiate numbers.', '谈数字前先对齐激励。'),
          S('We will follow up with a clean written summary.', '我们会给出清晰书面总结。'),
        ],
        expressions: [
          S('Here is what we can commit to today.', '这是我们今天能承诺的。'),
          S('Here is what we need from you to move faster.', '要更快推进，我们需要你们提供什么。'),
          S('Let’s separate commercial terms from execution planning.', '把商务条款与执行计划分开。'),
          S('We are flexible on structure if economics work.', '若经济模型成立，结构可谈。'),
          S('Trust is built through predictable delivery.', '信任来自可预测交付。'),
          S('We will protect your brand as if it were ours.', '我们会像保护自己品牌一样保护你们。'),
          S('If timelines slip, we will communicate early.', '若时间线滑档，我们会早沟通。'),
          S('Let’s schedule a working session with operators.', '我们约一场与执行同学的工作会。'),
        ],
        vocabulary: [
          S('incentive', '激励'),
          S('commercial terms', '商务条款'),
          S('execution', '执行'),
          S('transparency', '透明'),
          S('predictability', '可预测性'),
          S('alignment', '对齐'),
          S('operator', '执行负责人'),
          S('working session', '工作会话'),
        ],
        dialogue: [
          D('Partner', 'Can you guarantee exclusivity?', '能保证排他吗？'),
          D('You', 'Not globally — but we can discuss limited exclusivity by region.', '非全球——但可谈区域有限排他。'),
          D('Partner', 'What is the MOQ?', 'MOQ 多少？'),
          D('You', 'Let’s align on velocity first, then set MOQ tiers.', '先对齐动销，再定 MOQ 阶梯。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：合作意向会议收尾',
          brief: '总结共识、列出开放问题、约下次会议与交付物。',
          prompts: ['三段式收尾', '明确 homework', '表达长期意图'],
        },
        simulation: {
          titleZh: '模拟：对方提出不合理排他',
          context: '礼貌拒绝并给替代方案。',
          objectives: ['认可诉求', '解释约束', '给选项'],
        },
        reflectionQuestions: [
          '哪一句让你听起来更像「谈合作的人」而非学生？',
          '你今天是否过度道歉？哪句可以改成中性陈述？',
          '写下一句你常用的「长期合作」英文表达。',
        ],
        oralTaskZh: '跟读 6 句合作导向句型，并加你自己的行业词。',
      },
      {
        dayInWeek: 6,
        themeZh: '演示与讲故事：产品价值',
        themeEn: 'Product story for business rooms',
        todayFocus: 'The key feature is portability and speed.',
        shadowing: [
          S('This product is designed for content creators.', '这款产品为内容创作者设计。'),
          S('It solves a real pain point in mobile shooting.', '解决移动拍摄的真实痛点。'),
          S('The key feature is portability and speed.', '核心特性是便携与速度。'),
          S('Users can go from bag to shooting in under a minute.', '用户可在一分钟内从包到开拍。'),
          S('We validated demand with early adopters.', '我们用早期用户验证需求。'),
          S('Retailers like it because it turns quickly.', '零售商喜欢因为它周转快。'),
          S('Our roadmap prioritizes reliability over gimmicks.', '路线图优先可靠而非噱头。'),
        ],
        expressions: [
          S('Let me show the workflow in sixty seconds.', '我用六十秒展示工作流。'),
          S('This is the before state; this is the after state.', '这是之前；这是之后。'),
          S('The ROI is fewer reshoots and faster posting.', 'ROI 是少重拍、更快发布。'),
          S('We are happy to share sell-through data.', '我们乐意分享动销数据。'),
          S('We built this for real shoots, not demos.', '为真实拍摄而非演示而做。'),
          S('If you want, we can run a pilot in three stores.', '若愿意，可在三家店试点。'),
          S('The risk is low — the upside is incremental revenue.', '风险低——上行是增量收入。'),
          S('Questions — what would you like to stress-test?', '提问——你想压力测试哪一点？'),
        ],
        vocabulary: [
          S('workflow', '工作流'),
          S('pain point', '痛点'),
          S('sell-through', '动销'),
          S('pilot', '试点'),
          S('incremental', '增量'),
          S('reliability', '可靠性'),
          S('adopter', '采用者'),
          S('gimmick', '噱头'),
        ],
        dialogue: [
          D('Buyer', 'Why not the cheaper alternative?', '为何不选更便宜替代品？'),
          D('You', 'Cheaper breaks faster — returns eat margin.', '更便宜更容易坏——退货吃掉利润。'),
          D('Buyer', 'Show me proof.', '给我看证据。'),
          D('You', 'Here is return-rate data by retailer cohort.', '这是按零售商队列的退货率数据。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：60 秒产品演示口播',
          brief: '无幻灯片，只用嘴：用户—痛点—方案—证据—下一步。',
          prompts: ['控制时间', '少形容词', '以一个数字结尾'],
        },
        simulation: {
          titleZh: '模拟：采购打断问价',
          context: '先稳住结构，再回答价格框架。',
          objectives: ['不慌乱', '先价值后价格', '约数据跟进'],
        },
        reflectionQuestions: [
          '你的「一句话产品定义」英文版是什么？',
          '哪个技术词应该换成业务词？',
          '你今天的演示有没有清晰 CTA（下一步）？',
        ],
        oralTaskZh: '录三遍 60 秒演示，选最稳一遍保存。',
      },
      {
        dayInWeek: 7,
        themeZh: '第 2 周复盘：会议控场能力',
        themeEn: 'Week 2 review',
        todayFocus: 'I run meetings with outcomes, not vibes.',
        shadowing: [
          S('I run meetings with outcomes, not vibes.', '我开会要结果，不靠氛围。'),
          S('My default is: agenda, decisions, owners.', '我的默认：议程、决策、负责人。'),
          S('I am learning to interrupt politely.', '我在学习礼貌打断。'),
          S('I want my questions to sharpen thinking.', '我希望提问能让思考更锋利。'),
          S('Written follow-ups reduce misunderstandings.', '书面跟进减少误解。'),
          S('Next week I will practice negotiation language.', '下周我练谈判语言。'),
          S('Consistency beats intensity.', '稳定胜过爆发。'),
        ],
        expressions: [
          S('This week I improved how I close meetings.', '本周我改进了会议收尾方式。'),
          S('I still talk too long when nervous.', '紧张时我仍会说太久。'),
          S('I will prepare three clarifying questions per meeting.', '每场会准备三个澄清问题。'),
          S('I want my updates to be shorter and sharper.', '我希望更新更短更利。'),
          S('I will practice summarizing decisions in one minute.', '我练一分钟总结决策。'),
          S('I need more reps with native speakers.', '我需要更多与母语者练习次数。'),
          S('I will record one real meeting snippet weekly.', '我每周录一段真实会议片段。'),
          S('Progress feels slow until it compounds.', '复利前进步感很慢。'),
        ],
        vocabulary: [
          S('outcome', '结果'),
          S('clarifying question', '澄清问题'),
          S('interrupt', '打断'),
          S('summary', '总结'),
          S('misunderstanding', '误解'),
          S('snippet', '片段'),
          S('compound', '复利'),
          S('intensity', '强度'),
        ],
        dialogue: [
          D('Mentor', 'What changed in your meetings?', '你的会议哪里变了？'),
          D('You', 'I end with decisions, not open loops.', '我以决策结束，不留开放环。'),
          D('Mentor', 'What is next?', '下一步？'),
          D('You', 'Negotiation reps and harder objections.', '谈判练习与更难异议。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：两分钟周复盘',
          brief: '英文总结：会议控场收获 + 一个失败时刻 + 下周目标。',
          prompts: ['具体例子', '可执行', '语气平静'],
        },
        simulation: {
          titleZh: '模拟：董事会成员问你本周管理动作',
          context: '用英文给一句战略级总结 + 一句执行级细节。',
          objectives: ['分层表达', '不堆砌', '可验证'],
        },
        reflectionQuestions: [
          '本周你最常用的三个会议动词是什么？（align / decide / escalate…）',
          '哪场「如果重来」你会更早收口决策？',
          '下周你要删除哪种无效会议习惯？',
        ],
        oralTaskZh: '写 8 条 action items 英文模板，朗读并各造一个真句。',
      },
    ],
  },
  {
    weekNumber: 3,
    weeklyGoal: '把「异议、谈判、条款」练到能稳住节奏：先理解、再交换条件、再落到文字。',
    focusAbility: '谈判用语、条件交换、邮件确认条款。',
    themes: '价格 / 付款 / MOQ / 试点',
    weeklyReviewTask: '用英文写一段「条款摘要」给你的合伙人（8–12 句）。',
    ceoWeeklyFocus: '本周 CEO 表达重点：用条款语言保护现金流与交付确定性。',
    days: [
      {
        dayInWeek: 1,
        themeZh: '询价与价格压力',
        themeEn: 'Pricing pressure',
        todayFocus: 'We need better pricing.',
        shadowing: [
          S('We need better pricing to make the partnership sustainable.', '我们需要更好价格让合作可持续。'),
          S('Our unit economics are tight at the current terms.', '当前条款下单位经济很紧。'),
          S('We are not asking for charity — we are asking for alignment.', '不是要施舍——要对齐。'),
          S('If pricing moves, we can commit to higher volume.', '价格能动，我们可承诺更高量。'),
          S('Let’s discuss tiered pricing by quarterly volume.', '我们按季度量级谈阶梯价。'),
          S('We can also explore marketing co-investment.', '也可探讨联合营销投入。'),
          S('We want a win-win structure.', '我们要双赢结构。'),
        ],
        expressions: [
          S('Can you walk me through how you built this price?', '能说说这价格怎么来的吗？'),
          S('What flexibility do you have on MOQ?', 'MOQ 上有什么弹性？'),
          S('If we prepay, what discount is realistic?', '若预付，现实折扣是多少？'),
          S('We need a path to net-thirty.', '我们需要走向 net-30 的路径。'),
          S('Let’s separate list price from effective price.', '把标价与实际价分开。'),
          S('We can trade margin for exclusivity — within limits.', '可在限度内用毛利换排他。'),
          S('If this is your floor, what else can move?', '若这是底价，还有什么可动？'),
          S('Let’s put numbers in writing before we celebrate.', '庆祝前先把数字写下来。'),
        ],
        vocabulary: [
          S('unit economics', '单位经济'),
          S('tiered pricing', '阶梯定价'),
          S('prepay', '预付'),
          S('net-30', '30 天账期'),
          S('list price', '标价'),
          S('effective price', '实际价'),
          S('floor', '底价'),
          S('rebate', '返利'),
        ],
        dialogue: [
          D('Supplier', 'This is already aggressive.', '这已经很有诚意。'),
          D('You', 'I understand — on our side, shelf timing is the constraint.', '理解——我们这边货架时间是硬约束。'),
          D('You', 'If you can improve 3%, we can increase the PO by 20%.', '若能改善 3%，我们可把订单量提高 20%。'),
          D('Supplier', 'Send it in writing.', '书面确认。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：要求更好价格',
          brief: '给出理由（经济模型/量/时间）并提出交换条件。',
          prompts: ['先肯定关系', '再谈约束', '再提方案'],
        },
        simulation: {
          titleZh: '模拟：对方强硬不让价',
          context: '你要探索非价格变量。',
          objectives: ['问隐藏变量', '提议试点', '约书面'],
        },
        reflectionQuestions: [
          '你今天哪一句「要价」最稳？',
          '哪句太冲？如何改成更合作语气？',
          '写下你的三条「交换条件」英文。',
        ],
        oralTaskZh: '跟读 6 句价格谈判句，并替换真实数字区间（可用假数据）。',
      },
      {
        dayInWeek: 2,
        themeZh: '付款条件与现金流',
        themeEn: 'Payment terms',
        todayFocus: 'Can we revisit the payment terms?',
        shadowing: [
          S('Can we revisit the payment terms?', '能否重谈付款条件？'),
          S('The current terms are difficult for us operationally.', '当前条款对我们运营困难。'),
          S('Cash conversion cycle is a real constraint.', '现金转换周期是真实约束。'),
          S('We propose a milestone-based schedule.', '我们建议按里程碑付款。'),
          S('We can accept a deposit with balanced milestones.', '可接受定金 + 平衡里程碑。'),
          S('We need predictability on invoicing.', '我们需要开票节奏可预测。'),
          S('Let’s align penalties for late delivery as well.', '也对延迟交付约定罚则对齐。'),
        ],
        expressions: [
          S('We need more flexibility on payment cadence.', '付款节奏需要更多弹性。'),
          S('Can we move from prepay to net-thirty after three successful shipments?', '三次顺利发货后能否从预付转 net-30？'),
          S('We are willing to offer a volume commitment in exchange.', '我们愿用量级承诺交换。'),
          S('Let’s cap exposure for both sides.', '给双方风险设上限。'),
          S('If currency fluctuates, how do we adjust?', '汇率波动如何调整？'),
          S('Please clarify VAT and duties in the quote.', '报价里请澄清增值税与关税。'),
          S('We need the contract to match what we discussed.', '合同需与讨论一致。'),
          S('Let’s involve finance on both sides.', '让双方财务一起参与。'),
        ],
        vocabulary: [
          S('milestone', '里程碑'),
          S('deposit', '定金'),
          S('invoice', '发票'),
          S('cadence', '节奏'),
          S('exposure', '风险敞口'),
          S('currency', '汇率/货币'),
          S('duties', '关税'),
          S('contract', '合同'),
        ],
        dialogue: [
          D('Finance', 'We require 100% prepay for new customers.', '新客户要 100% 预付。'),
          D('You', 'We can do 30% deposit if you extend net-thirty after shipment.', '若发货后给 net-30，我们可以 30% 定金。'),
          D('Finance', 'Show your credit references.', '给信用背书。'),
          D('You', 'I will send references and last year financials.', '我会发背书与去年财报摘要。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：和财务谈账期',
          brief: '用「风险—对等—机制」结构谈条件。',
          prompts: ['先理解对方政策', '再给对等承诺', '落到条款'],
        },
        simulation: {
          titleZh: '模拟：对方要求全额预付',
          context: '你要争取里程碑或信用机制。',
          objectives: ['不激化', '给证据', '给选项'],
        },
        reflectionQuestions: [
          '哪一句让你感觉「像在和 CFO 说话」？',
          '你能否用两句英文解释你们现金流约束？',
          '明天你要跟进的一封邮件主题行是什么？',
        ],
        oralTaskZh: '朗读付款条款相关 8 词，并各造句。',
      },
      {
        dayInWeek: 3,
        themeZh: 'MOQ、交期与供应链对齐',
        themeEn: 'MOQ & lead time',
        todayFocus: 'We need more flexibility on MOQ.',
        shadowing: [
          S('We need more flexibility on MOQ for the pilot phase.', '试点阶段需要 MOQ 弹性。'),
          S('Lead time is the bottleneck for our launch window.', '交期是我们上线窗口的瓶颈。'),
          S('If MOQ drops, we can move faster on sell-through learning.', 'MOQ 降低能更快学习动销。'),
          S('We can consolidate SKUs to simplify manufacturing.', '可合并 SKU 简化制造。'),
          S('Let’s align on safety stock responsibilities.', '对齐安全库存责任。'),
          S('We need a clear escalation path if shipments slip.', '若发货延误需要清晰升级路径。'),
          S('We prefer honesty over optimistic dates.', '宁可诚实也不要乐观日期。'),
        ],
        expressions: [
          S('What is the realistic lead time, not the best case?', '现实交期是什么，不是最好情况？'),
          S('Can we split the PO into two shipments?', '能否拆两批发货？'),
          S('If we commit to X, what MOQ can you support?', '若我们承诺 X，你们能支持什么 MOQ？'),
          S('Let’s document penalties and remedies.', '把罚则与补救写清楚。'),
          S('We need visibility into raw material constraints.', '需要看到原材料约束可见性。'),
          S('If you need forecasts, we will share weekly.', '若要预测，我们按周分享。'),
          S('Let’s set a joint operations review.', '设联合运营复盘。'),
          S('We can accept higher MOQ after validation.', '验证通过后可接受更高 MOQ。'),
        ],
        vocabulary: [
          S('lead time', '交期'),
          S('safety stock', '安全库存'),
          S('SKU', '单品'),
          S('forecast', '预测'),
          S('shipment', '发货'),
          S('remedy', '补救措施'),
          S('constraint', '约束'),
          S('validation', '验证'),
        ],
        dialogue: [
          D('Ops', 'MOQ is fixed for tooling reasons.', '因模具原因 MOQ 固定。'),
          D('You', 'Can we share tooling across two SKUs?', '能否两个 SKU 共用模具？'),
          D('Ops', 'Possible — but it changes the timeline.', '可能——但会改变时间线。'),
          D('You', 'Let’s compare total cost and schedule risk.', '比较总成本与排期风险。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：供应链周会',
          brief: '你是创始人，对齐交期、MOQ、风险与补救。',
          prompts: ['先事实', '再选项', '再决策'],
        },
        simulation: {
          titleZh: '模拟：工厂说「要加钱才能插队」',
          context: '你要评估并决定是否接受。',
          objectives: ['问清原因', '要书面', '设上限'],
        },
        reflectionQuestions: [
          '今天哪句英文最能压住场面但不失礼？',
          '你如何描述「交期风险」的业务影响？',
          '写一句你下次要用的 escalation 句式。',
        ],
        oralTaskZh: '跟读供应链 7 句，替换为你真实供应商语境。',
      },
      {
        dayInWeek: 4,
        themeZh: '异议处理：先对齐再推进',
        themeEn: 'Objections',
        todayFocus: 'I understand your concern.',
        shadowing: [
          S('I understand your concern — let me reflect it back.', '我理解你的顾虑——让我复述确认。'),
          S('From our side, this is a major issue as well.', '从我们这侧这也是重大问题。'),
          S('I don’t think this solution is workable without changes.', '不改的话这方案不太可行。'),
          S('Let’s find a middle ground that protects both sides.', '找保护双方的中间方案。'),
          S('We need to be practical here.', '这里要务实。'),
          S('What would a workable version look like for you?', '对你可行的版本是什么样？'),
          S('If we can agree on principles, details get easier.', '原则一致，细节更容易。'),
        ],
        expressions: [
          S('Help me understand the constraint behind that.', '帮我理解背后的约束。'),
          S('I agree with the problem; I disagree with the solution.', '我同意问题；不同意方案。'),
          S('Let’s separate must-haves from nice-to-haves.', '把必须有和最好有分开。'),
          S('We can pilot before we commit fully.', '全量承诺前可先试点。'),
          S('If we concede here, we need something back.', '若这里让步，需要换回什么。'),
          S('Let’s pause and reconvene tomorrow with options.', '暂停，明天带方案再开。'),
          S('I appreciate the directness.', '感谢直接。'),
          S('We are not walking away — we are problem-solving.', '不是走人——在解题。'),
        ],
        vocabulary: [
          S('objection', '异议'),
          S('constraint', '约束'),
          S('middle ground', '中间地带'),
          S('concession', '让步'),
          S('must-have', '必须有'),
          S('pilot', '试点'),
          S('reconvene', '再开会'),
          S('principle', '原则'),
        ],
        dialogue: [
          D('Partner', 'Your MOQ is too high for our test.', '你们 MOQ 对我们测试太高。'),
          D('You', 'Fair — what volume would make the test meaningful for you?', '合理——什么量级对你们测试有意义？'),
          D('Partner', 'Five hundred units.', '500 件。'),
          D('You', 'If you commit to marketing placements, we can support 500.', '若承诺营销资源位，我们可以支持 500。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：处理价格异议',
          brief: '对方说太贵，你要复述、对齐价值、给结构选项。',
          prompts: ['复述', '问标准', '给两档方案'],
        },
        simulation: {
          titleZh: '模拟：对方用竞争对手压价',
          context: '不贬低对手，强调差异与风险。',
          objectives: ['冷静', '对比框架', '要约书面'],
        },
        reflectionQuestions: [
          '哪一句「复述异议」最自然？',
          '你今天有没有抢话？如何避免？',
          '写下两个英文「交换条件」模板。',
        ],
        oralTaskZh: '练习「I understand… / From our side… / What if…」三连，造真实句。',
      },
      {
        dayInWeek: 5,
        themeZh: '冲突升级：对事不对人',
        themeEn: 'Conflict without drama',
        todayFocus: "Let's find a middle ground.",
        shadowing: [
          S('I want to address this directly and respectfully.', '我想直接且尊重地谈这件事。'),
          S('The pattern I am seeing is missed deadlines without early flags.', '我看到的模式是延误但没有早标记。'),
          S('That impacts customers and partner trust.', '这影响客户与伙伴信任。'),
          S('I am not questioning your effort.', '我不质疑你的努力。'),
          S('I need a different operating cadence going forward.', '往后我需要不同的运营节奏。'),
          S('If we cannot align, we will change staffing.', '若无法对齐，我们会调整人手。'),
          S('Let’s reset expectations today.', '今天重置期望。'),
        ],
        expressions: [
          S('This is the impact on the business.', '这是对业务的影响。'),
          S('Here is the behavior I need to see.', '这是我需要看到的行为。'),
          S('Can you commit to this cadence?', '你能承诺这个节奏吗？'),
          S('If you push back, tell me now.', '若要反对，现在说。'),
          S('I will support you, but I will not accept surprises.', '我会支持你，但不接受意外。'),
          S('Let’s document a performance improvement plan.', '我们记录绩效改进计划。'),
          S('I want weekly written updates until stable.', '稳定前我要每周书面更新。'),
          S('We can revisit in thirty days.', '30 天后再复盘。'),
        ],
        vocabulary: [
          S('pattern', '模式'),
          S('trust', '信任'),
          S('cadence', '节奏'),
          S('staffing', '人员配置'),
          S('PIP', '绩效改进计划'),
          S('surprise', '意外'),
          S('reset', '重置'),
          S('respectful', '尊重的'),
        ],
        dialogue: [
          D('Manager', 'The team is burned out.', '团队燃尽了。'),
          D('You', 'Burnout is real — we will cut two initiatives.', '燃尽真实——我们砍掉两个项目。'),
          D('You', 'But communication standards are non-negotiable.', '但沟通标准不让步。'),
          D('Manager', 'Understood — I will implement weekly risk flags.', '明白——我会做每周风险标记。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：艰难对话开场',
          brief: '用「事实—影响—请求」结构，语气稳定。',
          prompts: ['避免你怎样', '聚焦可观察行为', '给支持'],
        },
        simulation: {
          titleZh: '模拟：对方激动反驳',
          context: '你要降温和复述。',
          objectives: ['停顿', '复述', '回到标准'],
        },
        reflectionQuestions: [
          '哪一句最难说出口？练到不抖为止。',
          '你如何英文表达边界而不羞辱对方？',
          '今天学到的最稳冲突句式是什么？',
        ],
        oralTaskZh: '朗读 6 句艰难对话句式，录音听语气是否过尖或过软。',
      },
      {
        dayInWeek: 6,
        themeZh: '邮件锁定条款：减少口头误解',
        themeEn: 'Written terms',
        todayFocus: 'Per our discussion, please confirm.',
        shadowing: [
          S('Per our discussion, please confirm the following terms.', '根据讨论，请确认以下条款。'),
          S('If anything is incorrect, reply by EOD.', '若有误，今日下班前回复。'),
          S('Silence will be treated as confirmation of this summary.', '沉默视为确认本摘要。'),
          S('We will proceed with manufacturing upon written approval.', '收到书面批准后启动生产。'),
          S('Please include incoterms and payment schedule.', '请包含贸易术语与付款计划。'),
          S('We will attach the latest pricing sheet.', '附上最新价格表。'),
          S('Thanks for moving quickly — timing matters.', '感谢快速推进——时间关键。'),
        ],
        expressions: [
          S('This email captures decisions only — not new asks.', '本邮件只记录决策——不含新诉求。'),
          S('Please do not interpret verbal side comments as commitments.', '请勿把口头旁白当承诺。'),
          S('Any change requires written approval from both sides.', '任何变更需双方书面批准。'),
          S('We need a single source of truth in the contract.', '合同里要单一真相来源。'),
          S('Let’s avoid scope creep via email threads.', '避免邮件串导致范围蔓延。'),
          S('If urgent, call — don’t negotiate only in chat.', '紧急请电话——别只在聊天里谈。'),
          S('We will loop in legal for final language.', '终稿语言会抄送法务。'),
          S('Appreciate partnership — let’s keep it professional.', '感谢合作——保持专业。'),
        ],
        vocabulary: [
          S('confirmation', '确认'),
          S('incoterms', '贸易术语'),
          S('approval', '批准'),
          S('scope creep', '范围蔓延'),
          S('source of truth', '唯一真相来源'),
          S('verbal', '口头的'),
          S('commitment', '承诺'),
          S('manufacturing', '制造'),
        ],
        dialogue: [
          D('You', 'Summary: price, MOQ, lead time, payment.', '摘要：价格、MOQ、交期、付款。'),
          D('Partner', 'Payment needs one tweak.', '付款要微调。'),
          D('You', 'Understood — please propose exact language.', '明白——请给出准确措辞。'),
          D('You', 'No production until both sign.', '双方签署前不投产。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：口头念出邮件摘要',
          brief: '把条款摘要大声读出来，检查是否清楚、无歧义。',
          prompts: ['慢速', '分条', '结尾要确认请求'],
        },
        simulation: {
          titleZh: '模拟：对方在邮件里偷偷加条件',
          context: '你要礼貌纠正并坚持流程。',
          objectives: ['指出差异', '引用会议', '要求修订'],
        },
        reflectionQuestions: [
          '哪类条款你最需要用英文讲清楚？',
          '你今天是否把「假设」说成了「承诺」？如何改？',
          '写一句你常用的邮件确认收尾英文。',
        ],
        oralTaskZh: '写一段 10 句以内的 terms summary，并朗读两遍。',
      },
      {
        dayInWeek: 7,
        themeZh: '第 3 周复盘：谈判语感',
        themeEn: 'Week 3 review',
        todayFocus: 'I negotiate with calm structure.',
        shadowing: [
          S('I negotiate with calm structure, not loud emotion.', '我用冷静结构谈判，不靠大声情绪。'),
          S('I am learning to trade concessions deliberately.', '我在学习有意识地交换让步。'),
          S('I want every term tied to a business reason.', '我希望每个条款都有业务理由。'),
          S('Written summaries save relationships.', '书面摘要拯救关系。'),
          S('Silence is a tool — I do not have to fill it.', '沉默是工具——不必填满。'),
          S('Next week I will practice leadership storytelling.', '下周我练领导力叙事。'),
          S('Reps turn fear into fluency.', '重复把怕变成流利。'),
        ],
        expressions: [
          S('This week I improved how I ask for payment terms.', '本周我改善了要账期的问法。'),
          S('I still rush when I feel pressed.', '压力下我仍会急。'),
          S('I will prepare a negotiation one-pager before calls.', '电话前准备谈判一页纸。'),
          S('I want three fallback options ready.', '准备三个备选方案。'),
          S('I will practice saying no with alternatives.', '练习带替代方案说不。'),
          S('I need more role-play with realistic objections.', '需要更真实异议的角色扮演。'),
          S('I will debrief every negotiation in five minutes.', '每场谈判后五分钟复盘。'),
          S('Small improvements compound.', '小改进会复利。'),
        ],
        vocabulary: [
          S('concession', '让步'),
          S('fallback', '备选'),
          S('debrief', '复盘'),
          S('objection', '异议'),
          S('fluency', '流利'),
          S('emotion', '情绪'),
          S('structure', '结构'),
          S('relationship', '关系'),
        ],
        dialogue: [
          D('Peer', 'What was your toughest moment?', '最难时刻？'),
          D('You', 'They pushed prepay — I held and traded volume.', '他们推预付——我拿量换。'),
          D('Peer', 'What will you repeat?', '你会重复什么？'),
          D('You', 'Written recap every time.', '每次都书面复盘。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：周复盘（谈判线）',
          brief: '两分钟：本周一次真实谈判/讨论的英文复盘。',
          prompts: ['结果', '失误', '下次机制'],
        },
        simulation: {
          titleZh: '模拟：合伙人问你「这周谈成了什么」',
          context: '用英文回答：条款 + 风险 + 下一步。',
          objectives: ['不夸大', '可验证', '有行动'],
        },
        reflectionQuestions: [
          '本周你最大的谈判收获一句英文总结？',
          '你最常回避的英文句子是什么？下周直面它。',
          '哪条条款下次要更早抛出来？',
        ],
        oralTaskZh: '列出 5 个 negotiation verbs（propose / concede / anchor…）并各造句。',
      },
    ],
  },
  {
    weekNumber: 4,
    weeklyGoal: '把「战略叙事 + 跨文化沟通 + 英文领导力」打通：能说清取舍，也能主持高难度对话。',
    focusAbility: '战略表达、愿景、跨文化敏感、英文汇报结构。',
    themes: '战略 / 愿景 / 组织 / 文化',
    weeklyReviewTask: '录一段 3 分钟英文「季度优先级」演讲，并自评结构与用词。',
    ceoWeeklyFocus: '本周 CEO 表达重点：让别人听懂你的取舍，而不是只听你的忙碌。',
    days: [
      {
        dayInWeek: 1,
        themeZh: '战略优先级：为什么是现在',
        themeEn: 'Strategic priorities',
        todayFocus: 'Our priority this quarter is market expansion.',
        shadowing: [
          S('Our priority this quarter is market expansion.', '本季度优先级是市场扩张。'),
          S('We need to strengthen our brand positioning in retail.', '需要加强零售端品牌定位。'),
          S('The biggest opportunity is in offline retail execution.', '最大机会在线下零售执行。'),
          S('We should focus on categories with long-term potential.', '聚焦长期潜力品类。'),
          S('This is not only a product decision, but a strategic decision.', '这不仅是产品决策，更是战略决策。'),
          S('We will deprioritize distractions that do not move the needle.', '砍掉不推动关键指标的干扰项。'),
          S('We will communicate the strategy clearly to the global team.', '向全球团队清晰沟通战略。'),
        ],
        expressions: [
          S('We are choosing focus over breadth.', '选择专注而非铺广度。'),
          S('The cost of delay is shelf space.', '延迟的代价是货架。'),
          S('We need a crisp strategy narrative for the US team.', '美国团队需要利落的战略叙事。'),
          S('Let’s align on what we will not do.', '对齐我们不做什么。'),
          S('Resources follow strategy — not the reverse.', '资源跟随战略——不是反过来。'),
          S('If we try to do everything, we ship nothing.', '若什么都做，什么也上不了。'),
          S('I want dissent in private; alignment in public.', '私下可异议，公开要对齐。'),
          S('Execution requires fewer goals, not more slogans.', '执行需要更少目标，不是更多口号。'),
        ],
        vocabulary: [
          S('priority', '优先级'),
          S('positioning', '定位'),
          S('execution', '执行'),
          S('category', '品类'),
          S('strategic', '战略的'),
          S('trade-off', '权衡'),
          S('narrative', '叙事'),
          S('dissent', '异议'),
        ],
        dialogue: [
          D('Exec', 'Why not double down online only?', '为何不只做线上？'),
          D('You', 'Online builds awareness; retail builds trust and velocity.', '线上做认知；零售做信任与速度。'),
          D('Exec', 'What do we stop?', '我们停什么？'),
          D('You', 'We stop two experimental SKUs and one side project.', '停两个实验 SKU 和一个旁支项目。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：对美国团队讲「本季打法」',
          brief: '3 分钟：优先级—不做什么—需要什么支持。',
          prompts: ['开场一句结论', '中间两个证据', '结尾一个请求'],
        },
        simulation: {
          titleZh: '模拟：高管挑战你「太保守」',
          context: '用风险框架回答，不防御过度。',
          objectives: ['承认观点', '解释约束', '提出试点'],
        },
        reflectionQuestions: [
          '你的战略叙事是否能用 5 个英文关键词概括？',
          '哪句「不做什么」最难说出口？',
          '美国同事最可能误解你哪一点？如何预防？',
        ],
        oralTaskZh: '朗读模块 G 句型并替换为你公司真实战略词。',
      },
      {
        dayInWeek: 2,
        themeZh: '愿景与文化：跨团队对齐',
        themeEn: 'Vision & culture',
        todayFocus: 'We build for the long term.',
        shadowing: [
          S('We build for the long term, not quarterly hype.', '我们做长期，不做季度 hype。'),
          S('Our culture rewards ownership and clarity.', '文化奖励主人翁与清晰。'),
          S('We hire for judgment, not just skills.', '我们招判断力，不只是技能。'),
          S('We communicate with respect across time zones.', '跨时区也要尊重沟通。'),
          S('We prefer written clarity for decisions.', '决策偏好书面清晰。'),
          S('We celebrate learning from mistakes — once.', '我们庆祝从错误学习——一次。'),
          S('We want leaders who raise risks early.', '希望领导者早抬风险。'),
        ],
        expressions: [
          S('This is how we operate at scale.', '这是我们规模化运作的方式。'),
          S('If this is unclear, tell me — I will fix it.', '若不清楚告诉我——我会修正。'),
          S('I expect async updates and synchronous decisions.', '要异步更新，同步决策。'),
          S('We will not tolerate silent slips.', '不容忍沉默式滑档。'),
          S('Diversity of thought makes strategy stronger.', '思想多元让战略更强。'),
          S('English fluency is not required; clarity is.', '不要求英语花哨；要求清晰。'),
          S('Let’s assume good intent and verify with facts.', '假设善意并用事实验证。'),
          S('We win as a team — functions do not throw over the wall.', '团队赢——部门不把问题扔过墙。'),
        ],
        vocabulary: [
          S('vision', '愿景'),
          S('culture', '文化'),
          S('ownership', '主人翁'),
          S('judgment', '判断力'),
          S('async', '异步'),
          S('synchronous', '同步'),
          S('diversity', '多元'),
          S('intent', '意图'),
        ],
        dialogue: [
          D('US Lead', 'The team feels priorities shift too often.', '团队觉得优先级常变。'),
          D('You', 'Fair — we changed twice due to supply shocks.', '合理——供应链冲击我们调整了两次。'),
          D('You', 'Going forward: monthly strategy notes + frozen weekly goals.', '往后：月度战略备忘 + 周目标冻结。'),
          D('US Lead', 'That helps — thanks.', '有帮助——谢谢。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：全员信口头版',
          brief: '把一封「文化/协作原则」信念成 90 秒口语。',
          prompts: ['三条原则', '一条例子', '一条请求'],
        },
        simulation: {
          titleZh: '模拟：跨文化误解（直接 vs 委婉）',
          context: '解释你的沟通风格并邀请反馈。',
          objectives: ['不自责过度', '设规则', '要例子'],
        },
        reflectionQuestions: [
          '你希望团队记住你的一句英文价值观是什么？',
          '哪种跨文化误会你最常遇到？',
          '下周你要改的一个沟通习惯（英文）？',
        ],
        oralTaskZh: '背诵 5 句文化对齐句式，各改写成你的版本。',
      },
      {
        dayInWeek: 3,
        themeZh: '英文汇报结构：金字塔原理',
        themeEn: 'Executive readout',
        todayFocus: 'Headline, evidence, ask.',
        shadowing: [
          S('Headline: we are on track, with two risks.', '结论：在轨道上，有两个风险。'),
          S('Evidence: sell-through improved week over week.', '证据：动销周环比改善。'),
          S('Risk one: supplier lead time variance.', '风险一：供应商交期方差。'),
          S('Risk two: marketing spend efficiency.', '风险二：营销花费效率。'),
          S('Ask: approve incremental budget for retail activations.', '诉求：批零售激活的增量预算。'),
          S('If we delay, we lose seasonal timing.', '若延迟会错过季节窗口。'),
          S('I will send a one-page appendix after this.', '会后发一页附录。'),
        ],
        expressions: [
          S('If you only remember one thing, remember this.', '若只记一件事，记这个。'),
          S('Let me separate facts from interpretation.', '把事实与解读分开。'),
          S('Here is what changed since last week.', '与上周相比变化是什么。'),
          S('I need a decision on X by Y.', '需要在 Y 前对 X 决策。'),
          S('Happy to take questions now or async.', '现在或异步提问都可以。'),
          S('I will not bury the lead.', '我不会把结论埋到最后。'),
          S('This is the downside scenario.', '这是 downside 情景。'),
          S('This is the upside scenario if execution holds.', '若执行稳住，这是 upside。'),
        ],
        vocabulary: [
          S('headline', '标题/结论先行'),
          S('evidence', '证据'),
          S('appendix', '附录'),
          S('interpretation', '解读'),
          S('downside', '下行风险'),
          S('upside', '上行空间'),
          S('activation', '激活/落地活动'),
          S('variance', '方差/波动'),
        ],
        dialogue: [
          D('Board', 'What would you do with more capital?', '钱多你会做什么？'),
          D('You', 'Accelerate retail placements and hire US ops earlier.', '加速零售点位并更早招美国运营。'),
          D('Board', 'Biggest risk?', '最大风险？'),
          D('You', 'Execution bandwidth — mitigated by hiring and fewer initiatives.', '执行带宽——用招聘与更少项目缓释。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：5 分钟英文汇报',
          brief: '严格按 headline / evidence / risks / ask 结构。',
          prompts: ['每部分计时', '避免背稿腔', '结尾重复 ask'],
        },
        simulation: {
          titleZh: '模拟：被打断追问细节',
          context: '你要「停车场」处理并回到主线。',
          objectives: ['不失礼貌', '承诺跟进', '继续主线'],
        },
        reflectionQuestions: [
          '你汇报时最容易省略的部分是什么？（风险还是诉求）',
          '哪句英文连接词最有用？',
          '把今天的汇报压缩成 30 秒版本。',
        ],
        oralTaskZh: '录音 headline 10 遍，直到像「你在讲结论」而不是在读稿。',
      },
      {
        dayInWeek: 4,
        themeZh: '轻社交与关系建立（高层场景）',
        themeEn: 'Relationship signal',
        todayFocus: "It's great to finally meet in person.",
        shadowing: [
          S('It’s great to finally meet in person.', '终于线下见面太好了。'),
          S('How has your week been?', '你这周怎么样？'),
          S('I’ve been traveling quite a bit lately.', '我最近出差不少。'),
          S('Thanks for making time today.', '感谢你今天抽时间。'),
          S('I’ve heard a lot of good things about your team.', '久闻你们团队很棒。'),
          S('I admire how you scaled distribution in the Midwest.', '我很欣赏你们在中西部分销的扩张。'),
          S('I’d love to learn what you are optimizing for this year.', '想了解你们今年最优化什么。'),
        ],
        expressions: [
          S('I prefer candid conversations.', '我偏好坦诚对话。'),
          S('What does success look like for you in this partnership?', '这段合作对你成功的样子是什么？'),
          S('Where do you see the biggest friction?', '你看到最大摩擦在哪里？'),
          S('If helpful, I can share what worked in China.', '如需要，我可以分享中国有效做法。'),
          S('I don’t need a perfect answer today — I need honesty.', '今天不需要完美答案——要诚实。'),
          S('Let’s keep building trust step by step.', '我们一步步建立信任。'),
          S('I’m excited about what we can build together.', '很期待一起做出东西。'),
          S('Coffee next time — I’ll bring data, you bring constraints.', '下次咖啡——我带数据，你带约束。'),
        ],
        vocabulary: [
          S('candid', '坦诚'),
          S('friction', '摩擦/阻力'),
          S('partnership', '合作'),
          S('trust', '信任'),
          S('optimize', '优化'),
          S('scale', '扩张'),
          S('constraint', '约束'),
          S('admire', '欣赏'),
        ],
        dialogue: [
          D('Partner', 'What motivates you as a founder?', '作为创始人你的动力？'),
          D('You', 'Building products that creators actually use every day.', '做创作者每天真会用的产品。'),
          D('Partner', 'What worries you?', '你担心什么？'),
          D('You', 'Moving too slow in retail — timing is everything.', '零售太慢——时机就是一切。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：会议前的 3 分钟 small talk',
          brief: '自然过渡到业务问题，不尬聊太久。',
          prompts: ['一个真诚夸奖', '一个开放式问题', '一个轻量个人分享'],
        },
        simulation: {
          titleZh: '模拟：对方问敏感政治/文化话题',
          context: '礼貌转移回业务与共同目标。',
          objectives: ['不辩论', '不冒犯', '转回合作'],
        },
        reflectionQuestions: [
          '哪句寒暄最像你，而不是背模板？',
          '你如何英文表达真诚而不油腻？',
          '下次见面你要记住对方哪一个小细节？',
        ],
        oralTaskZh: '跟读模块 H 句型，替换为你真实行程与话题。',
      },
      {
        dayInWeek: 5,
        themeZh: '跨文化反馈：直接但不伤人',
        themeEn: 'Cross-cultural feedback',
        todayFocus: 'I may be direct — that means I respect your time.',
        shadowing: [
          S('I may be direct — that means I respect your time.', '我可能很直接——这代表我尊重你的时间。'),
          S('In my culture, clarity is kindness.', '在我的文化里，清晰是善意。'),
          S('If my tone feels sharp, please tell me.', '若语气尖锐请告诉我。'),
          S('I want us to assume good intent.', '希望我们假设善意。'),
          S('Let’s separate style from substance.', '把风格与实质分开。'),
          S('If something is unclear, I will ask twice.', '不清楚我会问第二次。'),
          S('We can agree on communication norms for this team.', '我们可以为团队约定沟通规范。'),
        ],
        expressions: [
          S('When I push, I am pushing the problem — not you.', '我施压是对问题，不是对你。'),
          S('Help me calibrate what “urgent” means on your side.', '帮我校准你们侧的「紧急」。'),
          S('I prefer written decisions after verbal alignment.', '口头对齐后要书面决策。'),
          S('Let’s use a shared glossary for key terms.', '关键术语用共享词汇表。'),
          S('If I interrupt, it is to keep time — not to dominate.', '若打断是为控时——不是压制。'),
          S('Feedback is a gift — I want yours too.', '反馈是礼物——我也想要你的。'),
          S('Let’s debrief cultural friction early.', '文化摩擦要早复盘。'),
          S('We will adjust — culture is a system.', '我们会调整——文化是系统。'),
        ],
        vocabulary: [
          S('calibrate', '校准'),
          S('norm', '规范'),
          S('glossary', '词汇表'),
          S('friction', '摩擦'),
          S('intent', '意图'),
          S('substance', '实质'),
          S('tone', '语气'),
          S('debrief', '复盘'),
        ],
        dialogue: [
          D('US PM', 'Your messages feel demanding.', '你的消息显得很强硬。'),
          D('You', 'Thanks for telling me — I will add context and soften openings.', '感谢提醒——我会补充背景并软化开头。'),
          D('US PM', 'Also, fewer pings after midnight.', '也少在半夜狂 ping。'),
          D('You', 'Agreed — I will batch updates and respect boundaries.', '同意——我会批量更新并尊重边界。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：建立团队沟通规范',
          brief: '用英文提出三条规范并征求同意。',
          prompts: ['先讲目的', '再讲规则', '再问是否 OK'],
        },
        simulation: {
          titleZh: '模拟：你觉得对方太委婉导致不确定',
          context: '你要请求更明确的 yes/no。',
          objectives: ['不指责文化', '要清晰标准', '给模板'],
        },
        reflectionQuestions: [
          '你哪种中文沟通习惯最容易翻译成「生硬英文」？',
          '哪句软化语对你最有用？',
          '你需要团队遵守的一条英文沟通规则是什么？',
        ],
        oralTaskZh: '写三条 team communication norms 英文，朗读到顺口。',
      },
      {
        dayInWeek: 6,
        themeZh: '危机沟通：稳定与可预期',
        themeEn: 'Crisis comms',
        todayFocus: 'Here is what we know, what we do not know, and next update time.',
        shadowing: [
          S('Here is what we know, what we do not know, and when we will update next.', '已知、未知、下次更新时间。'),
          S('Customer trust depends on timely honesty.', '客户信任依赖及时诚实。'),
          S('We activated the incident response process.', '我们启动了事故响应流程。'),
          S('The root cause is still under investigation.', '根因仍在调查。'),
          S('We will not speculate publicly.', '公开场合不猜测。'),
          S('We are prioritizing affected customers first.', '优先处理受影响客户。'),
          S('I own the communication cadence during incidents.', '事故期间我负责沟通节奏。'),
        ],
        expressions: [
          S('Impact: severity, scope, and timeline.', '影响：严重度、范围、时间线。'),
          S('Mitigation steps are in progress.', '缓释措施进行中。'),
          S('We will post an update every two hours.', '每两小时更新。'),
          S('If you are affected, contact this channel.', '若受影响联系此渠道。'),
          S('We apologize for the disruption.', '对中断致歉。'),
          S('We will publish a postmortem within five business days.', '五个工作日内发布事后复盘。'),
          S('No blame in the moment — solve first.', '当下不追责——先解决。'),
          S('I am available for partner calls today.', '今天我可参加伙伴电话会。'),
        ],
        vocabulary: [
          S('incident', '事故'),
          S('postmortem', '事后复盘'),
          S('mitigation', '缓释'),
          S('scope', '范围'),
          S('severity', '严重度'),
          S('timeline', '时间线'),
          S('speculate', '猜测'),
          S('disruption', '中断'),
        ],
        dialogue: [
          D('Customer', 'Is our data safe?', '我们数据安全吗？'),
          D('You', 'We have no evidence of data exfiltration as of now.', '目前没有数据外泄证据。'),
          D('Customer', 'What should we do?', '我们该做什么？'),
          D('You', 'Rotate credentials now; we will confirm next steps by 6 p.m.', '先轮换凭证；我们下午 6 点前确认下一步。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：事故更新 60 秒',
          brief: '英文陈述：已知/未知/行动/下次更新。',
          prompts: ['不夸大', '不猜测', '给时间'],
        },
        simulation: {
          titleZh: '模拟：媒体/客户施压',
          context: '保持冷静边界，重复核心信息。',
          objectives: ['桥梁短语', '不陷入细节泥潭', '结束语'],
        },
        reflectionQuestions: [
          '哪句危机沟通英文最需要提前准备？',
          '你如何英文表达「仍在调查」而不显得逃避？',
          '写一条你团队的事故沟通原则（英文）。',
        ],
        oralTaskZh: '朗读危机沟通 6 句模板，各重复 5 遍。',
      },
      {
        dayInWeek: 7,
        themeZh: '第 4 周复盘：领导力英语总复盘',
        themeEn: 'Week 4 review',
        todayFocus: 'I speak like an operator who scales globally.',
        shadowing: [
          S('I speak like an operator who scales globally.', '我像能全球化扩张的经营者那样表达。'),
          S('I care about clarity, calm, and follow-through.', '我在意清晰、冷静与闭环。'),
          S('Language is a lever for trust and speed.', '语言是信任与速度的杠杆。'),
          S('I will keep training like I train the business.', '像训练业务一样训练语言。'),
          S('The next phase is deeper negotiation and leadership rooms.', '下一阶段是更深谈判与领导力场合。'),
          S('I am proud of showing up daily.', '我为每天出现而自豪。'),
          S('This is a marathon — I will pace myself.', '这是马拉松——我会配速。'),
        ],
        expressions: [
          S('Phase one built output confidence.', '第一阶段建立输出自信。'),
          S('I can run meetings and close loops.', '我能主持会议并闭环。'),
          S('I can negotiate terms without losing the relationship.', '能谈条款不失关系。'),
          S('I can communicate strategy with structure.', '能用结构讲战略。'),
          S('My edge is disciplined reps.', '我的优势是纪律性重复。'),
          S('I will keep a library of my best phrases.', '我会积累最佳短语库。'),
          S('I want English to feel boringly reliable.', '我要英语像可靠基础设施。'),
          S('Onward — with receipts.', '继续——用结果说话。'),
        ],
        vocabulary: [
          S('operator', '经营者/操盘手'),
          S('follow-through', '闭环跟进'),
          S('lever', '杠杆'),
          S('marathon', '马拉松'),
          S('pace', '配速'),
          S('discipline', '纪律'),
          S('receipts', '证据/结果'),
          S('confidence', '自信'),
        ],
        dialogue: [
          D('Coach', 'What is your 30-day commitment?', '你未来 30 天承诺？'),
          D('You', 'Daily shadowing plus one real English meeting push weekly.', '每日跟读 + 每周推一次真实英文会议场景。'),
          D('Coach', 'How will you measure it?', '如何衡量？'),
          D('You', 'Check-ins here + recorded reps + fewer “I will translate later” moments.', '打卡 + 录音 + 减少「稍后翻译」时刻。'),
        ],
        speakingTask: {
          titleZh: '角色扮演：阶段总结演讲 2 分钟',
          brief: '像对内对外路演一样总结阶段 1 收获与阶段 2 目标。',
          prompts: ['感谢团队', '三点收获', '三点下一步'],
        },
        simulation: {
          titleZh: '模拟：美国同事问你「接下来 90 天语言目标」',
          context: '用业务语言回答，可执行、可衡量。',
          objectives: ['具体', '谦逊', '坚定'],
        },
        reflectionQuestions: [
          '阶段 1 结束，你最自信的一项口语能力是什么？',
          '你最想在阶段 2（会议与管理）突破的一个场景？',
          '一句话给自己：为什么你要继续练下去？（英文）',
        ],
        oralTaskZh: '完整输出：2 分钟英文「创始人阶段复盘」，保存录音对比第 1 周。',
      },
    ],
  },
];
