/** 教材库：分类复习内容（内置完整示例） */

export const MATERIAL_CATEGORIES = [
  {
    id: 'meetings',
    title: '商务会议表达',
    subtitle: '开场、控场、对齐、收尾',
    patterns: [
      { en: "Let's get started — thanks everyone for making time.", zh: '开始会议并致谢到场。' },
      { en: "Today we'll focus on three key issues.", zh: '明确会议议程重心。' },
      { en: "First, let's review last week's progress.", zh: '回顾进展，建立上下文。' },
      { en: "What's the biggest blocker right now?", zh: '定位阻塞点。' },
      { en: "Let's align on the next steps and owners.", zh: '对齐下一步与负责人。' },
      { en: "I'll summarize decisions before we wrap.", zh: '收尾前总结决策。' },
    ],
    vocabulary: [
      { en: 'agenda', zh: '议程' },
      { en: 'action item', zh: '行动项' },
      { en: 'follow-up', zh: '跟进' },
      { en: 'timebox', zh: '限时讨论' },
      { en: 'parking lot', zh: '暂存问题清单' },
      { en: 'decision log', zh: '决策记录' },
      { en: 'stakeholder', zh: '相关方' },
      { en: 'sync', zh: '同步会议' },
    ],
    dialogue: [
      { speaker: 'You', en: "Let's timebox this to ten minutes.", zh: '我们把这段讨论控制在十分钟。' },
      { speaker: 'PM', en: 'The risk is scope creep on the integration.', zh: '风险是集成功能范围蔓延。' },
      { speaker: 'You', en: "Let's assign an owner and a deadline today.", zh: '今天就要指定负责人和截止日期。' },
    ],
    mistakes: [
      '避免只说 "OK" 结束议题；用 "So the decision is… / Next step is…" 收口。',
      '少用过长从句；拆成两句更利于跨文化理解。',
    ],
  },
  {
    id: 'management',
    title: '管理下属表达',
    subtitle: '布置、跟进、授权与支持',
    patterns: [
      { en: 'I need this completed by Friday EOD.', zh: '明确截止时间（周五下班前）。' },
      { en: 'Please send me an update by end of day.', zh: '当日汇报进展。' },
      { en: "Let's focus on execution this week.", zh: '强调执行与结果。' },
      { en: 'I want you to take ownership of this project.', zh: '明确授权与责任。' },
      { en: 'What support do you need from me?', zh: '询问资源与支持需求。' },
      { en: "Let's set a clear definition of done.", zh: '对齐完成标准。' },
    ],
    vocabulary: [
      { en: 'accountability', zh: '责任制' },
      { en: 'prioritization', zh: '优先级' },
      { en: 'bandwidth', zh: '精力/带宽' },
      { en: 'escalation', zh: '升级上报' },
      { en: 'rubric', zh: '评估标准' },
      { en: 'ramp-up', zh: '上手期' },
      { en: 'handoff', zh: '交接' },
      { en: 'cadence', zh: '节奏（周会/双周）' },
    ],
    dialogue: [
      { speaker: 'You', en: 'What is the single most important outcome this sprint?', zh: '这个迭代最重要的一项结果是什么？' },
      { speaker: 'Lead', en: 'Shipping the onboarding flow.', zh: '上线新手引导流程。' },
      { speaker: 'You', en: "Good — I'll remove two lower-priority tasks so you can focus.", zh: '好，我会拿掉两个低优任务让你专注。' },
    ],
    mistakes: [
      '避免模糊承诺 "soon / ASAP"；改成具体日期与时间区。',
      '批评时对事不对人：behavior + impact + expectation。',
    ],
  },
  {
    id: 'reporting',
    title: '汇报与反馈表达',
    subtitle: '结果、风险、需要决策的点',
    patterns: [
      { en: 'Here is the headline: we are on track for launch.', zh: '一句话结论先行。' },
      { en: 'The main risk is supplier lead time.', zh: '点出最大风险。' },
      { en: 'I need a decision on budget allocation by Thursday.', zh: '明确提出决策需求与时间点。' },
      { en: 'Feedback: the deck is strong, but the narrative needs a clearer "so what".', zh: '反馈要具体可改。' },
      { en: "Let's tighten the metrics section — fewer charts, more insight.", zh: '指导修改方向。' },
    ],
    vocabulary: [
      { en: 'north star metric', zh: '北极星指标' },
      { en: 'leading indicator', zh: '先行指标' },
      { en: 'lagging indicator', zh: '滞后指标' },
      { en: 'variance', zh: '偏差' },
      { en: 'mitigation', zh: '缓释措施' },
      { en: 'trade-off', zh: '权衡' },
      { en: 'ask', zh: '诉求/请求' },
      { en: 'readout', zh: '汇报摘要' },
    ],
    dialogue: [
      { speaker: 'You', en: 'Three updates: revenue, pipeline, and hiring.', zh: '三方面：收入、pipeline、招聘。' },
      { speaker: 'You', en: 'The ask: approve an additional $20k for paid tests.', zh: '诉求：批额外 2 万美金测试预算。' },
    ],
    mistakes: [
      '汇报不要从细节堆起；先结论，再证据，再下一步。',
      '反馈避免 "good job" 空泛；指出一个亮点 + 一个改进点。',
    ],
  },
  {
    id: 'negotiation',
    title: '商务谈判表达',
    subtitle: '价格、条款、合作节奏',
    patterns: [
      { en: 'We need better pricing to make the unit economics work.', zh: '用单位经济模型解释价格压力。' },
      { en: 'The current terms are difficult for us operationally.', zh: '说明条款对运营的困难。' },
      { en: 'We are looking for a long-term partnership, not a one-off deal.', zh: '强调长期合作框架。' },
      { en: 'Can we revisit the payment terms?', zh: '请求重谈付款条件。' },
      { en: 'We need more flexibility on MOQ.', zh: '起订量需要弹性。' },
      { en: 'What would it take to move to net-30?', zh: '探询对方条件切换门槛。' },
    ],
    vocabulary: [
      { en: 'MOQ', zh: '最小起订量' },
      { en: 'MSRP', zh: '建议零售价' },
      { en: 'rebate', zh: '返利' },
      { en: 'incoterms', zh: '国际贸易术语' },
      { en: 'liability cap', zh: '责任上限' },
      { en: 'SLA', zh: '服务等级协议' },
      { en: 'exclusivity', zh: '排他' },
      { en: 'volume tier', zh: '量级阶梯价' },
    ],
    dialogue: [
      { speaker: 'You', en: 'If we commit to 10k units per quarter, what pricing tier can you offer?', zh: '若我们承诺每季一万台，能给哪档价？' },
      { speaker: 'Partner', en: 'We can discuss a 6% rebate at that volume.', zh: '这个量级可以谈 6% 返利。' },
      { speaker: 'You', en: "Let's put milestones in writing and review quarterly.", zh: '把里程碑写清楚，按季度复盘。' },
    ],
    mistakes: [
      '不要一上来砍价；先对齐价值与约束，再谈数字。',
      '避免情绪化词；用 "difficult / challenging / need flexibility"。',
    ],
  },
  {
    id: 'office',
    title: '日常办公室沟通',
    subtitle: '异步、会议预约、跨时区协作',
    patterns: [
      { en: 'Looping in @Alex for visibility.', zh: '抄送相关人员同步信息。' },
      { en: 'Can we find a 30-minute slot this week?', zh: '预约短时间会议。' },
      { en: "I'm blocked on API access — can someone grant permissions?", zh: '说明阻塞并请求权限。' },
      { en: "I'll share a Loom walkthrough by tomorrow.", zh: '承诺异步视频说明。' },
      { en: 'Friendly reminder: the doc needs approval before Friday.', zh: '礼貌催办。' },
    ],
    vocabulary: [
      { en: 'FYI', zh: '供参考' },
      { en: 'EOD', zh: '当日结束' },
      { en: 'COB', zh: '下班前' },
      { en: 'PTO', zh: '带薪假' },
      { en: 'OOO', zh: '不在办公室' },
      { en: 'thread', zh: '消息串' },
      { en: 'unblock', zh: '排除阻塞' },
      { en: 'deck', zh: '演示文稿' },
    ],
    dialogue: [
      { speaker: 'You', en: "I'm in CET this week — can we do 4pm your time?", zh: '说明时差并给具体时间。' },
      { speaker: 'Colleague', en: 'Works for me — I’ll send a calendar invite.', zh: '可以，我来发日历邀请。' },
    ],
    mistakes: [
      '邮件主题要写清楚行动项：Action required / Decision needed。',
      '避免全大写催促；用 deadline + impact。',
    ],
  },
  {
    id: 'social',
    title: '小型社交 / 寒暄表达',
    subtitle: '建立信任与关系温度',
    patterns: [
      { en: 'How has your week been?', zh: '轻松开启对话。' },
      { en: "I've been traveling quite a bit lately.", zh: '交代近况，降低距离感。' },
      { en: "It's great to finally meet in person.", zh: '线下见面破冰。' },
      { en: 'Thanks for making time today.', zh: '感谢对方时间。' },
      { en: "I've heard a lot of good things about your team.", zh: '真诚夸奖对方团队。' },
    ],
    vocabulary: [
      { en: 'small talk', zh: '寒暄' },
      { en: 'rapport', zh: '融洽关系' },
      { en: 'icebreaker', zh: '破冰话题' },
      { en: 'common ground', zh: '共同点' },
      { en: 'follow-up coffee', zh: '约咖啡续聊' },
      { en: 'touch base', zh: '简短同步' },
      { en: 'cheers', zh: '干杯/致谢口语' },
      { en: 'pleasure', zh: '荣幸（正式场合）' },
    ],
    dialogue: [
      { speaker: 'You', en: 'Congrats on the retail launch — how did the first week feel?', zh: '祝贺并打开话题。' },
      { speaker: 'Partner', en: 'Chaotic but exciting.', zh: '忙乱但很兴奋。' },
      { speaker: 'You', en: "I'd love to hear what surprised you most.", zh: '引导对方多说。' },
    ],
    mistakes: [
      '寒暄避免过度私人问题；保持专业边界。',
      '不要只谈自己；多问对方一个具体问题。',
    ],
  },
  {
    id: 'product',
    title: '产品介绍表达',
    subtitle: '痛点、差异化、采用路径',
    patterns: [
      { en: 'This product is designed for content creators.', zh: '明确目标用户。' },
      { en: 'It solves a real pain point in mobile shooting.', zh: '痛点陈述。' },
      { en: 'The key feature is portability and speed.', zh: '核心卖点。' },
      { en: 'We believe this will be highly competitive in retail.', zh: '渠道与竞争判断。' },
      { en: 'Our goal is to improve workflow efficiency.', zh: '价值主张收束。' },
      { en: 'Here is a 60-second demo flow.', zh: '引导演示结构。' },
    ],
    vocabulary: [
      { en: 'value prop', zh: '价值主张' },
      { en: 'use case', zh: '使用场景' },
      { en: 'ROI', zh: '投资回报' },
      { en: 'adoption', zh: '采用率' },
      { en: 'onboarding', zh: '上手引导' },
      { en: 'retention', zh: '留存' },
      { en: 'SKU', zh: '单品编码' },
      { en: 'channel fit', zh: '渠道匹配度' },
    ],
    dialogue: [
      { speaker: 'You', en: 'Buyers care about margin and turn rate — we optimized both.', zh: '从采购视角谈利润与周转。' },
      { speaker: 'Buyer', en: 'What is your return rate in similar stores?', zh: '询问类似门店退货率。' },
      { speaker: 'You', en: 'Below category average — I can share the latest data pack.', zh: '给数据包增强可信度。' },
    ],
    mistakes: [
      '介绍产品先讲用户故事，再讲功能列表。',
      '避免夸大形容词堆砌；用可验证指标。',
    ],
  },
  {
    id: 'strategy',
    title: '战略沟通表达',
    subtitle: '优先级、取舍、长期方向',
    patterns: [
      { en: 'Our priority this quarter is market expansion.', zh: '本季度优先级。' },
      { en: 'We need to strengthen our brand positioning.', zh: '品牌定位升级。' },
      { en: 'The biggest opportunity is in offline retail.', zh: '指出机会赛道。' },
      { en: 'We should focus on categories with long-term potential.', zh: '强调长期品类。' },
      { en: 'This is not only a product decision, but a strategic decision.', zh: '抬升议题层级。' },
    ],
    vocabulary: [
      { en: 'north star', zh: '北极星目标' },
      { en: 'roadmap', zh: '路线图' },
      { en: 'moat', zh: '护城河' },
      { en: 'flywheel', zh: '飞轮' },
      { en: 'scenario planning', zh: '情景规划' },
      { en: 'capital allocation', zh: '资金配置' },
      { en: 'operating model', zh: '运营模式' },
      { en: 'ecosystem', zh: '生态' },
    ],
    dialogue: [
      { speaker: 'You', en: 'We will deprioritize two experiments to fund retail expansion.', zh: '说明取舍与资源投向。' },
      { speaker: 'Exec', en: 'What is the downside if we delay?', zh: '追问延迟风险。' },
      { speaker: 'You', en: 'We lose shelf timing — competitors will occupy the set.', zh: '用时间窗口解释风险。' },
    ],
    mistakes: [
      '战略沟通要给出 "why now" 与 "what we stop"。',
      '避免空泛 vision；落到指标与里程碑。',
    ],
  },
  {
    id: 'conflict',
    title: '冲突处理表达',
    subtitle: '异议、对齐、寻找中间方案',
    patterns: [
      { en: 'I understand your concern.', zh: '先确认理解对方顾虑。' },
      { en: 'From our side, this is a major issue.', zh: '表明己方严重性。' },
      { en: "I don't think this solution is workable.", zh: '明确不可行点。' },
      { en: "Let's find a middle ground.", zh: '提议寻找中间方案。' },
      { en: 'We need to be practical here.', zh: '拉回现实约束。' },
      { en: 'Can we test a smaller pilot first?', zh: '用试点降低冲突烈度。' },
    ],
    vocabulary: [
      { en: 'misalignment', zh: '不一致' },
      { en: 'escalation path', zh: '升级路径' },
      { en: 'de-escalate', zh: '降温' },
      { en: 'non-negotiable', zh: '不可让步项' },
      { en: 'concession', zh: '让步' },
      { en: 'BATNA', zh: '最佳替代方案' },
      { en: 'mediation', zh: '协调' },
      { en: 'reset', zh: '重启沟通框架' },
    ],
    dialogue: [
      { speaker: 'Partner', en: 'Your team missed two deadlines.', zh: '指责延误。' },
      { speaker: 'You', en: "You're right — here's the root cause and the prevention plan.", zh: '承认事实 + 原因 + 预防。' },
      { speaker: 'You', en: 'To rebuild trust, we propose weekly checkpoints for the next month.', zh: '提出修复机制。' },
    ],
    mistakes: [
      '冲突场景避免 over-apologize；用事实、责任、机制三段式。',
      '不要用 "you always"；改用具体事件与时间线。',
    ],
  },
];
