/**
 * 阶段 1 第 3–4 周（替换原文件中偏谈判/战略的周）：产品与日常沟通 → 简单会议整合与阶段复盘
 */
const S = (en, zh) => ({ en, zh });
const D = (speaker, en, zh) => ({ speaker, en, zh });

export const phase1Week3 = {
  weekNumber: 3,
  weeklyGoal:
    '在「敢开口」基础上，把产品介绍、办公室日常、轻社交串成一条线：别人能听懂你卖什么、你怎么协作、你怎么建立信任。',
  focusAbility: '产品一句话、渠道友好表达、异步沟通礼貌、寒暄不尬。',
  themes: '产品介绍 / 办公室英语 / 轻社交 / 简单对齐',
  weeklyReviewTask: '录音 90 秒：英文介绍产品 + 一个真实使用场景 + 一句邀请对方反馈。',
  ceoWeeklyFocus: '本周 CEO 表达重点：让别人 60 秒内知道「卖给谁、解决什么、为何现在」。',
  days: [
    {
      dayInWeek: 1,
      themeZh: '产品介绍：痛点、特性、采用路径',
      themeEn: 'Product pitch basics',
      todayFocus: 'This product is designed for content creators.',
      shadowing: [
        S('This product is designed for content creators.', '这款产品为内容创作者设计。'),
        S('It solves a real pain point in mobile shooting.', '解决移动拍摄里的真实痛点。'),
        S('The key feature is portability and speed.', '核心特性是便携与速度。'),
        S('We believe this will be highly competitive in retail.', '我们相信在零售端会很有竞争力。'),
        S('Our goal is to improve workflow efficiency.', '目标是提升工作流效率。'),
        S('We validated demand with early adopters and sell-through data.', '用早期用户与动销数据验证需求。'),
        S('If helpful, I can walk you through a sixty-second demo flow.', '如需要，我带你过一遍 60 秒演示流。'),
      ],
      expressions: [
        S('This is who it is for, and this is what it replaces.', '这是给谁用，替代什么。'),
        S('The before state is messy setup; the after state is one-tap ready.', '之前是搭建混乱，之后是一键就绪。'),
        S('Buyers care about margin, velocity, and returns — we optimized for all three.', '采购关心毛利、周转、退货——我们三者都优化。'),
        S('We can start with a small placement and scale with data.', '可先小范围上架，用数据放大。'),
        S('Happy to share a one-pager and a short Loom.', '乐意分享一页纸和短视频演示。'),
        S('What would make this a “must stock” for your set?', '什么能让这成为你们系列的必上款？'),
        S('We are not selling specs — we are selling outcomes.', '我们卖的不是参数，是结果。'),
        S('Let me know what proof you need to feel confident.', '告诉我你需要什么证据才放心。'),
      ],
      vocabulary: [
        S('placement', '上架/点位'),
        S('sell-through', '动销'),
        S('SKU', '单品'),
        S('assortment', '品类组合'),
        S('velocity', '周转速度'),
        S('margin', '毛利'),
        S('adopter', '早期采用者'),
        S('workflow', '工作流'),
      ],
      dialogue: [
        D('Buyer', 'Why should we care?', '我们为什么要关注？'),
        D('You', 'Because your shoppers already buy accessories — we improve conversion with faster setup.', '因为顾客本来买配件——我们让搭建更快从而提升转化。'),
        D('Buyer', 'What is the return risk?', '退货风险？'),
        D('You', 'Below category average in similar doors — I can share the latest cut.', '相似门店低于品类均值——我可分享最新切片。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：渠道采购的 60 秒介绍',
        brief: '无幻灯片：用户—痛点—方案—证据—下一步。',
        prompts: ['控制时间', '结尾只问一个开放问题'],
      },
      simulation: {
        titleZh: '模拟：对方说「我们货架很满」',
        context: '不硬推，先问对方品类策略，再谈试点。',
        objectives: ['先问后说', '给试点选项', '约数据跟进'],
      },
      reflectionQuestions: [
        '哪一句让你的产品听起来「像商品」而不是「像工程」？',
        '哪个技术词可以换成采购听得懂的词？',
        '你能否用 15 秒英文讲清 SKU 定位？',
      ],
      oralTaskZh: '跟读模块 F 句型，替换为你的产品线关键词，录音一遍。',
    },
    {
      dayInWeek: 2,
      themeZh: '办公室英语：请求、确认、礼貌催促',
      themeEn: 'Office comms',
      todayFocus: 'Could you update the thread by EOD?',
      shadowing: [
        S('Could you update the thread by EOD with the latest timeline?', '能否今日下班前在线程里更新最新时间线？'),
        S('I want to make sure I understood — are we aiming for Friday delivery?', '想确认我是否理解——目标是周五交付吗？'),
        S('If anything is unclear, please push back now.', '若有不清楚现在请反对。'),
        S('I will consolidate notes and share a recap.', '我会整理纪要并分享复盘。'),
        S('Thanks for the quick turnaround.', '感谢快速响应。'),
        S('Looping in finance for visibility.', '抄送财务同步信息。'),
        S('Let’s keep decisions in email, not only in chat.', '决策留在邮件，不只在聊天里。'),
      ],
      expressions: [
        S('Friendly reminder: we still need approval on X.', '友好提醒：我们仍需要 X 的批准。'),
        S('Blocking issue: waiting on access credentials.', '阻塞：等访问凭证。'),
        S('Can we book a fifteen-minute sync tomorrow?', '能否约明天 15 分钟同步？'),
        S('I am flexible — propose three slots.', '我可配合——给三个时间段。'),
        S('No need to apologize for delays — just give me the new date.', '延误不必过度道歉——给我新日期即可。'),
        S('Please confirm receipt so we are aligned.', '请确认收悉以便对齐。'),
        S('I will treat silence as “still working” unless told otherwise.', '若无回复我会当作仍在推进，除非另有说明。'),
        S('Appreciate everyone moving this forward.', '感谢大家推进。'),
      ],
      vocabulary: [
        S('thread', '消息串'),
        S('recap', '纪要'),
        S('turnaround', '周转/响应速度'),
        S('blocking', '阻塞'),
        S('credentials', '凭证'),
        S('sync', '同步会议'),
        S('slot', '时间段'),
        S('approval', '批准'),
      ],
      dialogue: [
        D('Ops', 'We might need one more day.', '可能要再多一天。'),
        D('You', 'Understood — what is the new ETA and what is still uncertain?', '了解——新 ETA 是什么，还有什么不确定？'),
        D('Ops', 'Supplier confirmation by tomorrow noon.', '供应商明天中午前确认。'),
        D('You', 'Please post that in the thread and tag me.', '请写在线程里并 @我。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：写「口头邮件」',
        brief: '把一封中文邮件的结构用英文说出来：背景 / 请求 / 截止 / 感谢。',
        prompts: ['每部分不超过两句'],
      },
      simulation: {
        titleZh: '模拟：同事一直已读不回',
        context: '礼貌升级，明确后果与时间。',
        objectives: ['先假设善意', '再给截止', '抄送相关人'],
      },
      reflectionQuestions: [
        '你今天最常用的礼貌催促句式是什么？',
        '哪句太软或太硬？如何微调？',
        '写一句你明天会用的「请确认」英文。',
      ],
      oralTaskZh: '朗读 6 句办公室模板，替换真实项目名。',
    },
    {
      dayInWeek: 3,
      themeZh: '简单会议：陈述现状与请求输入',
      themeEn: 'Light meeting speak-up',
      todayFocus: "Here's my update in three bullets.",
      shadowing: [
        S('Here is my update in three bullets.', '我用三条更新说明。'),
        S('First, what shipped; second, what is at risk; third, what I need.', '第一交付了什么；第二风险；第三我需要什么。'),
        S('I do not have a perfect answer yet — here is what we know.', '尚无完美答案——这是已知信息。'),
        S('I would like your input on the trade-off.', '希望你们对权衡给输入。'),
        S('If I am missing context, please correct me.', '若我缺上下文请纠正我。'),
        S('Let’s keep discussion focused on the decision today.', '讨论聚焦今天要做的决策。'),
        S('I will take the action item to follow up with legal.', '我来负责与法务跟进这项行动。'),
      ],
      expressions: [
        S('From my perspective, the risk is timeline, not scope.', '在我看来风险在时间线，不在范围。'),
        S('We can choose speed or polish — not both without more resources.', '要么速度要么打磨——资源不变无法兼得。'),
        S('Can we agree on a default if we run out of time?', '若时间不够能否同意默认方案？'),
        S('I suggest we timebox this to eight minutes.', '建议这段讨论限时八分钟。'),
        S('Let me repeat what I heard to ensure alignment.', '我复述听到的内容以确保对齐。'),
        S('I support this direction with one condition.', '我支持这个方向，有一个条件。'),
        S('I need more data before I can commit.', '需要更多数据我才能承诺。'),
        S('Happy to continue offline with design details.', '设计细节欢迎线下继续。'),
      ],
      vocabulary: [
        S('bullet', '要点条'),
        S('trade-off', '权衡'),
        S('default', '默认'),
        S('timebox', '限时'),
        S('commit', '承诺'),
        S('input', '输入/意见'),
        S('context', '上下文'),
        S('action item', '行动项'),
      ],
      dialogue: [
        D('You', 'Update: launch on track; risk is QA capacity.', '更新：上线在轨；风险是 QA 容量。'),
        D('Peer', 'Can we cut a feature?', '能砍功能吗？'),
        D('You', 'Yes — cut analytics v2; keep onboarding.', '可以——砍 analytics v2，保留 onboarding。'),
        D('You', 'Decision needed now: confirm the cut.', '现在需要决策：确认裁剪。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：周会 1 分钟更新',
        brief: '三条 bullet：完成 / 风险 / 需要支持。',
        prompts: ['不道歉开场', '结尾明确 ask'],
      },
      simulation: {
        titleZh: '模拟：你被打断问细节',
        context: '用「线下跟进」保护会议节奏。',
        objectives: ['认可问题', '提议线下', '回到决策'],
      },
      reflectionQuestions: [
        '你的「三条更新」英文模板固定下来了吗？',
        '哪一句连接词最有用？（First / Second / On the risk side）',
        '下次会议你要少说哪类废话？',
      ],
      oralTaskZh: '同一内容说两遍：一遍 45 秒，一遍 60 秒，练压缩与扩展。',
    },
    {
      dayInWeek: 4,
      themeZh: '电话与视频会议：开场、共享屏幕、确认下一步',
      themeEn: 'Calls & video',
      todayFocus: "Can everyone see my screen?",
      shadowing: [
        S('Can everyone see my screen and hear me clearly?', '大家能看到屏幕、听清我吗？'),
        S('I will keep this to fifteen minutes.', '我会控制在 15 分钟内。'),
        S('Let me share context in sixty seconds.', '我用 60 秒给背景。'),
        S('If you have questions, drop them in chat.', '有问题请打在聊天里。'),
        S('I will pause for clarifying questions at the end.', '最后留澄清提问时间。'),
        S('Let’s confirm owners and deadlines before we drop.', '挂断前确认负责人与截止。'),
        S('Thanks — I will send a recap right after.', '谢谢——我马上发纪要。'),
      ],
      expressions: [
        S('You are on mute.', '你静音了。'),
        S('Sorry — slight lag on my side.', '抱歉，我这边有点延迟。'),
        S('Let me reshare the link.', '我重新分享链接。'),
        S('Could you type the number in chat?', '能否把数字打在聊天里？'),
        S('Let’s move slides — next point is pricing.', '翻页——下一点是价格。'),
        S('I did not catch that — can you repeat?', '没听清——能重复吗？'),
        S('Let’s schedule a follow-up if we need deeper design review.', '若要更深设计评审我们另约。'),
        S('Great — aligned. Next step is…', '很好——对齐。下一步是…'),
      ],
      vocabulary: [
        S('mute', '静音'),
        S('lag', '延迟'),
        S('reshare', '重新分享'),
        S('clarifying', '澄清的'),
        S('recap', '纪要'),
        S('follow-up', '后续'),
        S('agenda', '议程'),
        S('deck', '演示文稿'),
      ],
      dialogue: [
        D('Host', 'We can’t hear you.', '听不到你。'),
        D('You', 'Sorry — unmuted now. Can you hear me?', '抱歉，已开麦。能听到吗？'),
        D('Host', 'Yes — go ahead.', '可以，请继续。'),
        D('You', 'Great — sharing screen now.', '好——正在共享屏幕。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：远程演示开场 45 秒',
        brief: '检查视听 → 时间盒 → 目标 → 开始演示。',
        prompts: ['英文要像操作手册一样清楚'],
      },
      simulation: {
        titleZh: '模拟：演示中对方频繁插问',
        context: '你要控场：先收问题，再统一答。',
        objectives: ['礼貌打断', '设规则', '继续主线'],
      },
      reflectionQuestions: [
        '你最顺口的「设备检查」英文是哪句？',
        '哪句在紧张时容易嘴瓢？练 10 遍。',
        '写一句你专用的会议收尾 + recap 承诺。',
      ],
      oralTaskZh: '跟读视频会议 7 句，模拟开麦关麦各一遍。',
    },
    {
      dayInWeek: 5,
      themeZh: '轻社交：建立信任但不油腻',
      themeEn: 'Light rapport',
      todayFocus: "I've heard a lot of good things about your team.",
      shadowing: [
        S('How has your week been?', '你这周怎么样？'),
        S("I've been traveling quite a bit lately.", '我最近出差不少。'),
        S("It's great to finally meet in person.", '终于线下见面太好了。'),
        S('Thanks for making time today.', '感谢今天抽时间。'),
        S("I've heard a lot of good things about your team.", '久闻你们团队很棒。'),
        S('I admire how you execute in retail.', '很欣赏你们在零售端的执行。'),
        S('I’d love to understand what you are optimizing for this quarter.', '想了解你们本季度最优化什么。'),
      ],
      expressions: [
        S('I prefer candid conversations — tell me what worries you.', '我偏好坦诚——告诉我你担心什么。'),
        S('If anything feels off, say it early — it saves time.', '若不对劲早说——省时间。'),
        S('We can keep small talk short and move to substance.', '寒暄可以短，尽快进入实质。'),
        S('I don’t need a perfect pitch — I need real constraints.', '不需要完美路演——我要真实约束。'),
        S('What would make this partnership successful for you?', '怎样算对你合作成功？'),
        S('I’ll follow up with a clean summary.', '我会发清晰摘要跟进。'),
        S('Coffee next time — I’ll bring data.', '下次咖啡我带数据。'),
        S('Appreciate the transparency.', '感谢透明。'),
      ],
      vocabulary: [
        S('rapport', '融洽关系'),
        S('candid', '坦诚'),
        S('substance', '实质内容'),
        S('constraint', '约束'),
        S('transparency', '透明'),
        S('partnership', '合作'),
        S('optimize', '优化'),
        S('execute', '执行'),
      ],
      dialogue: [
        D('Partner', 'Busy week — lots of launches.', '很忙——很多上新。'),
        D('You', 'Congrats — which launch surprised you most?', '恭喜——哪个上新最出乎意料？'),
        D('Partner', 'The accessories bundle.', '配件组合。'),
        D('You', 'Interesting — we see similar attach rates in our data.', '有意思——我们数据里也有类似搭售率。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：会议前三分钟寒暄',
        brief: '一个真诚夸奖 + 一个业务相关问题 + 过渡到议程。',
        prompts: ['不聊敏感私人话题'],
      },
      simulation: {
        titleZh: '模拟：对方过度闲聊',
        context: '礼貌收束到议程。',
        objectives: ['感谢', '定时间', '转正题'],
      },
      reflectionQuestions: [
        '哪句寒暄最像你本人？',
        '如何避免「套话感」？',
        '写一句你专用的「转入正题」英文。',
      ],
      oralTaskZh: '跟读模块 H 句型，替换为你的真实行程与业务。',
    },
    {
      dayInWeek: 6,
      themeZh: '把「听懂的」变成「说得出的」：复述与改写',
      themeEn: 'Paraphrase drills',
      todayFocus: 'Let me say that back in my own words.',
      shadowing: [
        S('Let me say that back in my own words.', '我用我的话复述一遍。'),
        S('If I understood correctly, your priority is speed.', '若我理解正确，你的优先级是速度。'),
        S('What I hear is risk on inventory, not demand.', '我听到的是库存风险，不是需求。'),
        S('Let me tighten my point — one sentence only.', '我把观点收紧——只一句。'),
        S('I will avoid long clauses and keep it simple.', '避免长从句，保持简单。'),
        S('Could you help me phrase this more naturally?', '能帮我说得更自然吗？'),
        S('I am practicing out loud on purpose.', '我有意大声练习。'),
      ],
      expressions: [
        S('In other words, we need a decision on X.', '换言之，我们需要对 X 决策。'),
        S('The simpler version is…', '更简单的版本是…'),
        S('Let me split this into two sentences.', '我拆成两句说。'),
        S('My point is not X — my point is Y.', '我的点不是 X，是 Y。'),
        S('Help me stress-test this wording.', '帮我压力测试这个措辞。'),
        S('I will record myself and listen for pacing.', '我会录音并听节奏。'),
        S('I want clarity over sophistication.', '要清晰不要花哨。'),
        S('Repetition is part of my job now.', '重复现在是我工作的一部分。'),
      ],
      vocabulary: [
        S('paraphrase', '复述改写'),
        S('clause', '从句'),
        S('wording', '措辞'),
        S('pacing', '节奏'),
        S('stress-test', '压力测试'),
        S('sophistication', '花哨/复杂'),
        S('priority', '优先级'),
        S('inventory', '库存'),
      ],
      dialogue: [
        D('Coach', 'Say the same idea in three levels: 10s, 30s, 60s.', '同一想法说三档：10/30/60 秒。'),
        D('You', '10s: We help creators shoot faster.', '10 秒：我们帮创作者拍更快。'),
        D('You', '30s: Portable rig, faster setup, better retail velocity.', '30 秒：便携、更快搭建、更好零售周转。'),
        D('Coach', 'Good — now slower, calmer.', '好——再慢一点、稳一点。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：三档长度练习',
        brief: '任选一业务点：10 / 30 / 60 秒英文各一遍。',
        prompts: ['计时', '不加速', '每档一个核心动词'],
      },
      simulation: {
        titleZh: '模拟：对方说「我没听懂」',
        context: '换一种结构再说，不堆更多词。',
        objectives: ['先问卡点', '再简化', '再确认'],
      },
      reflectionQuestions: [
        '今天最卡的复述点在哪里？',
        '你更喜欢短句还是从句？为什么？',
        '写一句你明天要用的「让我确认理解」英文。',
      ],
      oralTaskZh: '选 5 句今天教材，英文→中文→再英文复述，各一遍。',
    },
    {
      dayInWeek: 7,
      themeZh: '第 3 周复盘：产品 + 日常 + 社交输出',
      themeEn: 'Week 3 review',
      todayFocus: 'I can talk about my product without hiding behind jargon.',
      shadowing: [
        S('I can talk about my product without hiding behind jargon.', '我能不谈行话黑话讲清产品。'),
        S('I am more comfortable in meetings than last week.', '比上周更适应会议表达。'),
        S('I still need reps on phone openings.', '电话开场仍需重复练。'),
        S('Small talk feels less forced now.', '寒暄没那么勉强了。'),
        S('I will keep a phrase bank in my notes.', '我会在笔记里积累短语库。'),
        S('Next week I will integrate simple meeting control.', '下周整合简单会议控场。'),
        S('Consistency is becoming a competitive advantage.', '坚持本身在变成优势。'),
      ],
      expressions: [
        S('This week I improved product clarity.', '本周产品表达更清晰。'),
        S('I practiced async updates daily.', '我每天练异步更新。'),
        S('I want one real customer-facing rep next week.', '下周要一次真实客户场景练习。'),
        S('I will record one call snippet weekly.', '每周录一段通话片段。'),
        S('I am building English like a system.', '我把英语当系统建设。'),
        S('I celebrate small wins.', '庆祝小胜利。'),
        S('I will not compare myself to native speakers — I compare to yesterday.', '不和母语者比——和昨天比。'),
        S('Onward.', '继续。'),
      ],
      vocabulary: [
        S('jargon', '行话'),
        S('phrase bank', '短语库'),
        S('snippet', '片段'),
        S('async', '异步'),
        S('clarity', '清晰'),
        S('consistency', '坚持/一致性'),
        S('rep', '练习次数'),
        S('competitive advantage', '竞争优势'),
      ],
      dialogue: [
        D('Mentor', 'What is your one-line win?', '一句话收获？'),
        D('You', 'I can pitch the product in sixty seconds calmly.', '我能 60 秒平静讲完产品。'),
        D('Mentor', 'Next focus?', '下一步？'),
        D('You', 'Meeting control phrases — open, transition, close.', '会议控场短语——开场、过渡、收尾。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：90 秒周复盘',
        brief: '英文：产品表达进步 / 办公室英语进步 / 下周一个具体目标。',
        prompts: ['各 30 秒', '用例子'],
      },
      simulation: {
        titleZh: '模拟：合伙人问「这周英语练了什么」',
        context: '用业务语言回答，可对外复述。',
        objectives: ['具体', '可衡量', '有下周动作'],
      },
      reflectionQuestions: [
        '本周你最自豪的一句英文输出？',
        '哪类场景仍想逃避？下周排进日历。',
        '你的短语库新增了几条？写下来。',
      ],
      oralTaskZh: '整理本周 10 条最佳句型，朗读两遍并保存。',
    },
  ],
};

export const phase1Week4 = {
  weekNumber: 4,
  weeklyGoal:
    '把阶段 1 收口：你能完成「简单会议表达」闭环——开场、更新、追问、总结、跟进——并清楚知道自己的下一步训练焦点。',
  focusAbility: '会议模块 B 整合、复述确认、邮件式口头总结、阶段复盘。',
  themes: '会议主持基础 / 确认理解 / 总结跟进 / 阶段复盘',
  weeklyReviewTask: '录 3 分钟英文：模拟一场完整短会（开场-更新-决策-收尾），自我打分结构与语速。',
  ceoWeeklyFocus: '本周 CEO 表达重点：像主持会议一样组织你的英语句子。',
  days: [
    {
      dayInWeek: 1,
      themeZh: '会议开场：目标、议程、时间',
      themeEn: 'Open the room',
      todayFocus: "Let's get started.",
      shadowing: [
        S("Let's get started — thanks everyone for joining.", '开始，感谢参加。'),
        S("Today we'll focus on three key issues.", '今天聚焦三个关键议题。'),
        S('Goal: leave with decisions and owners.', '目标：带着决策与负责人离开。'),
        S('We have thirty minutes — I will timebox each topic.', '共 30 分钟——我会给每段限时。'),
        S('If we drift, I will bring us back.', '若跑题我会拉回。'),
        S('Please hold deep dives for offline.', '深度讨论请线下进行。'),
        S('First, quick updates — then decisions.', '先快速更新——再决策。'),
      ],
      expressions: [
        S('The purpose of this meeting is…', '会议目的是…'),
        S('We are not solving everything — we are deciding next steps.', '不求解决一切——要决定下一步。'),
        S('Let’s hear a two-minute update from each lead.', '每位负责人两分钟更新。'),
        S('After updates, we will decide A or B.', '更新后我们决定 A 或 B。'),
        S('I will capture actions live.', '我会现场记行动项。'),
        S('If you need to drop early, tell us now.', '若要早退现在说。'),
        S('Let’s respect speaking time.', '尊重发言时间。'),
        S('Great — let’s begin with product.', '好——从产品开始。'),
      ],
      vocabulary: [
        S('timebox', '限时'),
        S('deep dive', '深入讨论'),
        S('drift', '跑题'),
        S('decision', '决策'),
        S('owner', '负责人'),
        S('update', '更新'),
        S('agenda', '议程'),
        S('speaking time', '发言时间'),
      ],
      dialogue: [
        D('You', 'Agenda: launch risks, budget, next milestone.', '议程：上线风险、预算、下里程碑。'),
        D('Eng', 'Risk: third-party API instability.', '风险：第三方 API 不稳定。'),
        D('You', 'Decision needed: fallback vendor yes/no?', '需要决策：是否备用供应商？'),
        D('You', 'Decision: yes — owner: me; deadline: Friday.', '决策：要——负责人：我；截止：周五。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：主持 20 分钟会',
        brief: '完整走开场—更新—决策—收尾，可自问自答演练。',
        prompts: ['用连接词', '不断重复 owner / deadline'],
      },
      simulation: {
        titleZh: '模拟：有人迟到打断开场',
        context: '30 秒欢迎并重申议程与时间。',
        objectives: ['不抱怨', '重定调', '继续'],
      },
      reflectionQuestions: [
        '你的英文开场白固定下来了吗？',
        '哪句过渡最自然？',
        '如何避免会议里「中式长句」？',
      ],
      oralTaskZh: '跟读模块 B 句型，替换为你的真实会议主题。',
    },
    {
      dayInWeek: 2,
      themeZh: '进度回顾与阻塞提问',
      themeEn: 'Progress & blockers',
      todayFocus: "What's the biggest blocker right now?",
      shadowing: [
        S("First, let's review last week's progress.", '先回顾上周进展。'),
        S('What shipped? What did not — and why?', '交付了什么？什么没有——原因？'),
        S("What's the biggest blocker right now?", '当前最大阻塞？'),
        S('Is this a people issue, a process issue, or a priority issue?', '这是人的问题、流程问题还是优先级问题？'),
        S('What is the fastest path to unblock?', '最快解阻路径？'),
        S('Do we need a decision from me today?', '今天需要我做决策吗？'),
        S('Let’s assign owners before we move on.', '继续前指定负责人。'),
      ],
      expressions: [
        S('Give me red/yellow/green on your workstream.', '你的工作流红黄绿？'),
        S('Yellow means risk without intervention.', '黄表示不介入就有风险。'),
        S('I need names, not “the team”.', '我要名字，不要只说团队。'),
        S('If you are blocked, say it in the first minute.', '若阻塞第一分钟就说。'),
        S('Let’s not confuse motion with progress.', '别把动作当进展。'),
        S('What help do you need in the next forty-eight hours?', '48 小时内需要我什么帮助？'),
        S('If we cut scope, what do we cut?', '若砍范围砍什么？'),
        S('Let’s document the blocker in the thread.', '把阻塞写在线程里。'),
      ],
      vocabulary: [
        S('blocker', '阻塞'),
        S('workstream', '工作流'),
        S('intervention', '介入'),
        S('scope', '范围'),
        S('motion', '动作/空转'),
        S('document', '记录'),
        S('priority', '优先级'),
        S('process', '流程'),
      ],
      dialogue: [
        D('Lead', 'We are waiting on legal review.', '在等法务审。'),
        D('You', 'What is the minimum legal input to proceed?', '最低限度法务输入是什么才能继续？'),
        D('Lead', 'A one-paragraph disclaimer.', '一段免责声明。'),
        D('You', 'Owner: legal; deadline: tomorrow noon; I will ping.', '负责人：法务；截止：明天中午；我来催。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：追问阻塞直到可执行',
        brief: '每个阻塞以「负责人+日期+交付物」结尾。',
        prompts: ['不接受模糊', '语气稳定'],
      },
      simulation: {
        titleZh: '模拟：两人互相推责',
        context: '你要对齐事实与单一 owner。',
        objectives: ['复述时间线', '指定 owner', '写下来'],
      },
      reflectionQuestions: [
        '哪一句追问最有效？',
        '你如何英文表达「我要确定性」？',
        '写一个你专用的 blocker 模板句。',
      ],
      oralTaskZh: '跟读 7 句，替换为你团队真实项目名。',
    },
    {
      dayInWeek: 3,
      themeZh: '确认理解：复述、澄清、对齐',
      themeEn: 'Check understanding',
      todayFocus: 'Let me repeat what I heard.',
      shadowing: [
        S('Let me repeat what I heard.', '我复述我听到的。'),
        S('Did I get that right?', '我理解对吗？'),
        S('What I am hearing is…', '我听到的是…'),
        S('Help me close the gap — what am I missing?', '帮我补齐——我缺什么？'),
        S('Let’s align on definitions first.', '先对齐定义。'),
        S('When you say fast, do you mean this week or this month?', '你说快是指本周还是本月？'),
        S('Great — we are aligned.', '很好——我们对齐了。'),
      ],
      expressions: [
        S('Could you clarify what “done” means here?', '能澄清这里「完成」指什么吗？'),
        S('I want to avoid two teams working on the same task.', '避免两队做同一任务。'),
        S('Let’s write the definition of done in the doc.', '把完成定义写进文档。'),
        S('If assumptions change, we reset the plan.', '假设变就更改计划。'),
        S('Please push back if this is unrealistic.', '若不现实请反对。'),
        S('I prefer one uncomfortable conversation now over a failed launch later.', '宁可现在不舒服对话，也不要之后上线失败。'),
        S('Let’s confirm in writing after this call.', '会后书面确认。'),
        S('Thanks for correcting me.', '感谢纠正我。'),
      ],
      vocabulary: [
        S('clarify', '澄清'),
        S('definition of done', '完成定义'),
        S('assumption', '假设'),
        S('unrealistic', '不现实'),
        S('align', '对齐'),
        S('gap', '缺口'),
        S('reset', '重置'),
        S('confirm', '确认'),
      ],
      dialogue: [
        D('PM', 'We can launch Friday.', '周五能上线。'),
        D('You', 'When you say launch, is that GA or a beta cohort?', '你说上线指 GA 还是 beta 群？'),
        D('PM', 'Beta cohort — one hundred users.', 'Beta 群——100 用户。'),
        D('You', 'Got it — let’s label it clearly in comms.', '明白——沟通里要写清楚标签。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：澄清一个模糊承诺',
        brief: '用 5 个英文问句把「快/好/尽快」变具体。',
        prompts: ['日期', '范围', '质量标准'],
      },
      simulation: {
        titleZh: '模拟：跨文化「yes」其实不确定',
        context: '礼貌追问具体交付物。',
        objectives: ['不指责', '要例子', '要书面'],
      },
      reflectionQuestions: [
        '你今天最有效的澄清问句？',
        '哪种模糊词你最讨厌？如何用英文戳破？',
        '写一句会议里常用的「让我确认」英文。',
      ],
      oralTaskZh: '练「Let me repeat…」开头，接 5 种不同结尾（时间/人/范围/风险/下一步）。',
    },
    {
      dayInWeek: 4,
      themeZh: '总结与下一步：对齐行动项',
      themeEn: 'Close the loop',
      todayFocus: "Let's align on the next steps.",
      shadowing: [
        S("Let's align on the next steps.", '我们对齐下一步。'),
        S('Here are the decisions we made.', '这是我们做的决策。'),
        S('Action item: owner — deadline — deliverable.', '行动项：负责人—截止—交付物。'),
        S('If anything is unclear, speak now.', '若不清楚现在说。'),
        S('I will send a recap within one hour.', '我一小时内发纪要。'),
        S('Thanks — great discussion.', '谢谢——讨论很棒。'),
        S('Let’s execute — talk is cheap.', '执行吧——空谈便宜。'),
      ],
      expressions: [
        S('Recap: we decided X; next steps are Y.', '复盘：我们决定 X；下一步是 Y。'),
        S('Please react in the thread if I missed anything.', '若我有遗漏请在线程里指出。'),
        S('Silence means agreement on this summary.', '对本摘要沉默视为同意。'),
        S('Next meeting: Monday, same time, same link.', '下次会议：周一同时同链接。'),
        S('I will chase owners if items slip.', '若行动项滑档我会催负责人。'),
        S('Let’s keep momentum.', '保持势头。'),
        S('If you need me, ping me directly.', '需要我直接找我。'),
        S('Have a good one.', '祝顺利。'),
      ],
      vocabulary: [
        S('recap', '纪要/复盘'),
        S('deliverable', '交付物'),
        S('momentum', '势头'),
        S('chase', '催促'),
        S('slip', '滑档/延误'),
        S('react', '回应'),
        S('summary', '摘要'),
        S('execute', '执行'),
      ],
      dialogue: [
        D('You', 'Recap: cut feature A; keep launch date.', '复盘：砍功能 A；保持上线日。'),
        D('You', 'Owner: PM — ship spec tonight.', '负责人：PM——今晚出规格。'),
        D('Eng', 'Confirmed.', '确认。'),
        D('You', 'Great — I will post recap in Slack.', '好——我会在 Slack 发纪要。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：60 秒会议收尾',
        brief: '决策列表 + 三个行动项 + 下次会议 + 感谢。',
        prompts: ['不添加新话题'],
      },
      simulation: {
        titleZh: '模拟：结束时有人突然抛新问题',
        context: '停车场处理：认可—另约—不扩散。',
        objectives: ['不陷入', '约时间', '结束'],
      },
      reflectionQuestions: [
        '你的收尾模板固定了吗？',
        '如何避免「会后各说各话」？',
        '写一句你专用的 recap 承诺英文。',
      ],
      oralTaskZh: '完整说一遍收尾：决策→行动项→时间→感谢，录音。',
    },
    {
      dayInWeek: 5,
      themeZh: '邮件式口头汇报：Headline + bullets',
      themeEn: 'Spoken email',
      todayFocus: 'Headline: we are on track.',
      shadowing: [
        S('Headline: we are on track with two risks.', '结论：在轨道上，有两个风险。'),
        S('Bullet one: shipped features.', '要点一：已交付功能。'),
        S('Bullet two: risks and mitigations.', '要点二：风险与缓释。'),
        S('Bullet three: what I need from you.', '要点三：我需要你什么。'),
        S('If you want details, I will follow up async.', '若要细节我异步补充。'),
        S('My ask is a decision on budget by Thursday.', '诉求是周四前预算决策。'),
        S('Thanks — happy to take questions.', '谢谢——欢迎提问。'),
      ],
      expressions: [
        S('If you only remember one thing…', '若只记一件事…'),
        S('The data supports this direction.', '数据支持这个方向。'),
        S('The risk is real but manageable.', '风险真实但可控。'),
        S('I am not looking for praise — I need a decision.', '不是要表扬——要决策。'),
        S('Let me separate facts from interpretation.', '事实与解读分开。'),
        S('I will send a one-pager after this.', '会后发一页纸。'),
        S('Happy to stress-test this plan.', '欢迎压力测试这计划。'),
        S('No surprises — I flagged this early.', '无惊喜——我早标记了。'),
      ],
      vocabulary: [
        S('headline', '标题/结论先行'),
        S('bullet', '要点条'),
        S('mitigation', '缓释'),
        S('interpretation', '解读'),
        S('stress-test', '压力测试'),
        S('async', '异步'),
        S('budget', '预算'),
        S('decision', '决策'),
      ],
      dialogue: [
        D('Exec', 'Why should I approve?', '为何我要批？'),
        D('You', 'Because delay costs shelf timing — mitigated by a small budget bump.', '因为延迟损失货架窗口——小幅加预算可缓释。'),
        D('Exec', 'What is the downside?', '下行风险？'),
        D('You', 'If we do nothing, we miss the seasonal peak.', '若不做，错过季节高峰。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：2 分钟「口头邮件」',
        brief: '严格 headline + 3 bullets + ask。',
        prompts: ['每部分计时', '结尾重复 ask'],
      },
      simulation: {
        titleZh: '模拟：被打断问细节',
        context: '用「会后发附录」保护结构。',
        objectives: ['答一句', '承诺跟进', '回主线'],
      },
      reflectionQuestions: [
        '你最容易省略的是 bullets 还是 ask？',
        '哪句英文让你听起来像「汇报者」？',
        '把今天的汇报压缩成 30 秒版本。',
      ],
      oralTaskZh: '同一汇报说 60 秒与 120 秒两版，比较信息密度。',
    },
    {
      dayInWeek: 6,
      themeZh: '阶段 1 整合演练：从寒暄到收尾',
      themeEn: 'Integrated drill',
      todayFocus: 'I can run a clean fifteen-minute loop.',
      shadowing: [
        S('I can run a clean fifteen-minute loop: open, update, decide, close.', '我能跑通 15 分钟闭环：开场、更新、决策、收尾。'),
        S('I will keep sentences short on purpose.', '我有意保持句子短。'),
        S('I will pause instead of filling silence with filler words.', '用停顿代替废话填充沉默。'),
        S('I will write down phrases that worked.', '记下有效的短语。'),
        S('I treat English like a muscle.', '我把英语当肌肉练。'),
        S('I am building for global operations.', '在为全球化经营做准备。'),
        S('This is founder training, not school English.', '这是创始人训练，不是学校英语。'),
      ],
      expressions: [
        S('Open: purpose + agenda + time.', '开场：目的+议程+时间。'),
        S('Middle: updates + blockers + decisions.', '中段：更新+阻塞+决策。'),
        S('Close: recap + actions + next meeting.', '收尾：复盘+行动+下次会。'),
        S('If I forget a word, I describe it simply.', '忘词就用简单描述。'),
        S('I ask for feedback weekly.', '每周要反馈。'),
        S('I show up even when it is uncomfortable.', '不舒服也出现。'),
        S('I measure progress by reps, not feelings.', '用重复次数衡量进步，不靠感觉。'),
        S('Phase two will add management depth.', '第二阶段会加深管理深度。'),
      ],
      vocabulary: [
        S('loop', '闭环'),
        S('filler words', '填充词/废话'),
        S('muscle', '肌肉（比喻）'),
        S('operations', '经营/运营'),
        S('depth', '深度'),
        S('feedback', '反馈'),
        S('reps', '重复次数'),
        S('progress', '进步'),
      ],
      dialogue: [
        D('Coach', 'Run the loop now — out loud.', '现在大声跑一遍闭环。'),
        D('You', 'Purpose… agenda… updates… decision… recap…', '目的…议程…更新…决策…复盘…'),
        D('Coach', 'Slower. Calm CEO energy.', '更慢。冷静 CEO 气场。'),
        D('You', 'Purpose…', '目的…'),
      ],
      speakingTask: {
        titleZh: '角色扮演：15 分钟完整会议自演',
        brief: '一人分饰多角或用提纲自问自答，必须含决策与行动项。',
        prompts: ['录音', '回听只改一点'],
      },
      simulation: {
        titleZh: '模拟：阶段 1 结业「对你合伙人」陈述',
        context: '说明你将如何把英语训练接入真实业务节奏。',
        objectives: ['具体', '可坚持', '要支持'],
      },
      reflectionQuestions: [
        '阶段 1 结束，你最大的变化是什么？',
        '阶段 2 你最想攻下的第一个管理场景？',
        '一句话承诺：未来 30 天每天练什么？（英文）',
      ],
      oralTaskZh: '完整录音 3 分钟：Intro + meeting loop + 自我复盘，保存对比第 1 周。',
    },
    {
      dayInWeek: 7,
      themeZh: '第 4 周复盘：阶段 1 收官',
      themeEn: 'Phase 1 capstone',
      todayFocus: 'Phase 1 complete — I ship English like I ship product.',
      shadowing: [
        S('Phase one complete — I ship English like I ship product.', '阶段 1 完成——像做产品一样交付英语练习。'),
        S('I can introduce myself and my company clearly.', '我能清晰介绍自己和公司。'),
        S('I can run a short meeting with structure.', '我能结构化主持短会。'),
        S('I can write and speak updates with owners and dates.', '我能口头/文字更新并带负责人与日期。'),
        S('I built a phrase bank and I will keep using it.', '建了短语库并会持续用。'),
        S('Next, I will deepen management and negotiation rooms.', '接下来加深管理与谈判场景。'),
        S('I am proud of consistency.', '我为坚持自豪。'),
      ],
      expressions: [
        S('I am not fluent yet — I am operational.', '尚未流利——但已可用。'),
        S('Clarity is my standard.', '清晰是我的标准。'),
        S('I will keep daily reps.', '保持每日重复。'),
        S('I want English to be boringly reliable.', '我要英语像可靠基础设施。'),
        S('Global leadership starts with daily sentences.', '全球领导力从每日句子开始。'),
        S('I will celebrate this milestone and reset goals.', '庆祝里程碑并重设目标。'),
        S('Thank you, past me, for showing up.', '感谢过去的自己坚持出现。'),
        S('Onward to phase two.', '进入阶段 2。'),
      ],
      vocabulary: [
        S('operational', '可运作的'),
        S('milestone', '里程碑'),
        S('consistency', '坚持'),
        S('capstone', '收官'),
        S('reset', '重设'),
        S('celebrate', '庆祝'),
        S('leadership', '领导力'),
        S('phase', '阶段'),
      ],
      dialogue: [
        D('You', 'Phase 1 done — next is management depth.', '阶段 1 完成——下一个是管理深度。'),
        D('Peer', 'What is your metric?', '你的衡量指标？'),
        D('You', 'Daily check-in + weekly real-scenario rep.', '每日打卡 + 每周一次真实场景练习。'),
        D('Peer', 'Solid.', '扎实。'),
      ],
      speakingTask: {
        titleZh: '角色扮演：2 分钟阶段演讲',
        brief: '像对内路演：收获 / 指标 / 阶段 2 目标。',
        prompts: ['英文', '具体', '结尾要承诺'],
      },
      simulation: {
        titleZh: '模拟：美国同事问你下一阶段练什么',
        context: '用业务语言，不要学习细节堆砌。',
        objectives: ['场景化', '可执行', '邀请监督'],
      },
      reflectionQuestions: [
        '阶段 1 你最推荐给自己的一句英文座右铭？',
        '哪个模块你要放进「高频复习」？',
        '明天阶段 2 第一周第一天，你预设的焦点是什么？',
      ],
      oralTaskZh: '朗读阶段收官 7 句 + 自选创始人座右铭一句，录音保存。',
    },
  ],
};
